# Copyright (C) 2026, Advanced Micro Devices, Inc.
# SPDX-License-Identifier: BSD-3-Clause

"""Staging an HLS build request: the files and the script a synthesis runs, written to a
directory. It never runs a tool.

``stage_hls`` writes the request (``contributions.HlsSource``) relocatably: the top
as ``top.cpp``, each header under its path below its root, and ``script.tcl``, which
names only relative paths. The script is FinnLib's HLS recipe (``hls/hbc.tcl``) with
the simulation stages off: open a project, add the top with the C++14 flags and an
include directory per declared header's directory, set the top, open a solution,
set the part, create the clock, run the request's directives, synthesize. The part
is the one thing it does not state: it reads ``$part``, which whoever runs it sets
first (``finn.util.hls``), so the staged request, and its digest, are the same on
every machine and for every part.

A top FINN writes takes each AXIS port as an ``hls::stream`` of ``axis_type``: the
convention by which the C simulation's driver (``finn.harness.hls``) calls it from
its ABI alone.

Staging checks what it can without a tool: every quoted ``#include`` in the top and
the headers names a declared header, beside the including file or on the include
path; refusal only, as the RTL checker refuses (``rtl``). An angle-bracket include
is the tool's (``ap_int.h``, ``hls_stream.h``) and is not checked.
"""

from __future__ import annotations

import re
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

from finn.kernels.artifacts.contributions import HlsSource
from finn.kernels.artifacts.module import BuildError

#: The staged request's files, relative to its directory.
TOP = "top.cpp"
SCRIPT = "script.tcl"
#: The project and solution the script opens, below the staged directory.
PROJECT, SOLUTION = "project", "solution"
#: FinnLib's own flags for its HLS sources (``hls/hbc.tcl``), less its warnings.
CFLAGS = "-std=c++14 -O2"

_INCLUDE = re.compile(r'^\s*#\s*include\s*"([^"]+)"', re.MULTILINE)


def axis_type(width: int, last: bool) -> str:
    """The C++ type of one beat of an HLS top's AXIS port ``width`` bits wide, with its
    TLAST when ``last``: what HLS presents as ``<port>_TDATA`` (and ``_TLAST``). A top FINN
    writes takes its streams of these, so a driver that knows only the ABI can call it."""
    if last:
        return f"hls::axis_data<ap_uint<{width}>, AXIS_ENABLE_LAST>"
    return f"ap_uint<{width}>"


def quoted_includes(text: str) -> tuple[str, ...]:
    """The names ``text`` includes in quotes, in order."""
    return tuple(_INCLUDE.findall(text))


@dataclass(frozen=True)
class StagedHls:
    """A request written to ``directory``: its files relative to it, the script among them."""

    function: str
    directory: Path
    files: tuple[str, ...]


def include_path(source: HlsSource) -> tuple[str, ...]:
    """The include directories: each declared header's, once, in declared order."""
    return tuple(dict.fromkeys(str(PurePosixPath(item.path).parent) for item in source.headers))


def script(source: HlsSource) -> str:
    """The synthesis script of ``source``, relative to the staged directory; ``$part`` is
    set by whoever runs it."""
    flags = " ".join([CFLAGS, *(f"-I{directory}" for directory in include_path(source))])
    lines = [
        "# Generated by finn.kernels.artifacts.hls -- do not edit.",
        "# An HLS build request; run it with $part set to the part to synthesize for.",
        f"open_project -reset {PROJECT}",
        f'add_files -cflags "{flags}" {TOP}',
        f"set_top {source.function}",
        f"open_solution -reset {SOLUTION}",
        "set_part $part",
        f"create_clock -period {source.period_ns:g} -name default",
        *source.directives,
        "csynth_design",
        "exit",
    ]
    return "\n".join(lines) + "\n"


def _check_includes(source: HlsSource, contents: Mapping[str, bytes]) -> None:
    declared = set(contents) - {TOP}
    path = include_path(source)
    missing: list[str] = []
    for name, content in contents.items():
        here = str(PurePosixPath(name).parent)
        for included in quoted_includes(content.decode(errors="replace")):
            candidates = (here, *path)
            if not any(
                str(PurePosixPath(directory) / included) in declared for directory in candidates
            ):
                missing.append(f"{name} includes {included!r}")
    if missing:
        raise BuildError(
            f"{source.function} includes headers it does not declare: " + ", ".join(missing)
        )


def stage_hls(source: HlsSource, directory: Path, *, roots: Mapping[str, Path]) -> StagedHls:
    """Write ``source``'s top, headers and script into ``directory``; ``roots`` resolves each
    header's root. Refuses a quoted include no declared header satisfies."""
    contents: dict[str, bytes] = {TOP: source.top.encode()}
    for item in source.headers:
        root = roots.get(item.root)
        if root is None:
            raise BuildError(f"no source root resolves {item.root!r}")
        try:
            contents[item.path] = (Path(root) / item.path).read_bytes()
        except OSError as error:
            raise BuildError(f"header {Path(root) / item.path} cannot be read") from error
    _check_includes(source, contents)
    contents[SCRIPT] = script(source).encode()
    directory.mkdir(parents=True, exist_ok=True)
    for name, content in contents.items():
        target = directory / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)
    return StagedHls(source.function, directory, tuple(contents))


__all__ = [
    "CFLAGS",
    "axis_type",
    "SCRIPT",
    "StagedHls",
    "TOP",
    "include_path",
    "quoted_includes",
    "script",
    "stage_hls",
]
