# Copyright (C) 2026, Advanced Micro Devices, Inc.
# SPDX-License-Identifier: BSD-3-Clause

"""Lazy facade for canonical logical values and their pure operations.

Importing a scalar datatype or a Region must not also load composition,
validation and presentation algorithms. Public names retain their existing
identity and load their owning module only when requested.
"""

from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from finn.dataflow.model.logical.datatypes import (
        DatatypeError,
        QONNXDataType,
        canonical_qonnx_datatype,
        decode_datatype,
        encode_datatype,
        is_qonnx_datatype,
        qonnx_datatype_width,
        resolve_qonnx_datatype_name,
    )
    from finn.dataflow.model.logical.composition import (
        NetworkFragment,
        ParentBoundary,
        ParentConnection,
        compose_network,
        qualify_logical,
        qualify_network,
        qualify_region,
    )
    from finn.dataflow.model.logical.maps import (
        AffineRankMap,
        Coordinate,
        CoordinateSet,
        ExplicitCoordinateMap,
        FiniteCoordinateSet,
        IdentityCoordinateMap,
        InvalidMapError,
        MapCapabilityError,
        MaterializationLimitError,
        MaterializationRequired,
        OccurrenceAxis,
        RectangularDomain,
        SeparableAffineRequirements,
        UnboundDomainError,
        UnsupportedMapEncoding,
        ValidationCapabilityError,
        decode_coordinate_map,
        decode_coordinate_set,
        decode_requirement_rule,
        encode_coordinate_map,
        encode_coordinate_set,
        encode_requirement_rule,
    )
    from finn.dataflow.model.logical.region import (
        BeatSequence,
        BeatType,
        DataflowRegion,
        InputInterface,
        InternalInput,
        LogicalSchedule,
        NumericElementType,
        Operand,
        OutputInterface,
        Port,
        RegionInput,
        RegionRefused,
        ScheduledInputRequirements,
        ScheduledOutputAvailability,
        ScheduleLevel,
        element_width,
        is_element_type,
    )
    from finn.dataflow.model.logical.region_profiles import (
        CanonicalExtentProfile,
        ProfileCertificationError,
        ProfileCertificationIssue,
        direct_output_availability,
        explicit_beat_sequence,
        lexicographic_occurrence_to_field,
    )
    from finn.dataflow.model.logical.region_validation import (
        RegionValidationIssue,
        RegionValidationReport,
        is_structurally_well_formed,
        validate_region,
    )
    from finn.dataflow.model.logical.network import (
        BoundaryContract,
        ChannelSpec,
        DataflowNetwork,
        DirectConnection,
        Edge,
        EdgeTransport,
        FanoutMode,
        NetworkNode,
        OrderedChannel,
        PassCorrespondence,
        PositionMap,
        RegionEndpoint,
        SinkContract,
    )
    from finn.dataflow.model.logical.network_validation import (
        NetworkValidationBudget,
        NetworkValidationIssue,
        NetworkValidationReport,
        is_network_structurally_well_formed,
        validate_network,
    )
    from finn.dataflow.model.logical.refs import (
        DataflowOperandRef,
        NetworkOperandError,
        RegionInputRef,
        RegionOutputRef,
        resolve_input,
        resolve_output,
    )
    from finn.dataflow.model.logical.presentation import (
        boundary_presented_position_set,
        boundary_presented_positions,
        edge_presented_position_set,
        edge_presented_positions,
        exposing_boundaries,
        exposing_ports,
        unpresented_position_set,
        unpresented_positions,
    )
    from finn.dataflow.model.logical.results import (
        CompositionError,
        ImplementationPath,
        LogicalResult,
        NetworkResult,
        QualifiedChildResult,
        RegionResult,
    )

_EXPORT_GROUPS = {
    "finn.dataflow.model.logical.datatypes": (
        "DatatypeError",
        "QONNXDataType",
        "canonical_qonnx_datatype",
        "decode_datatype",
        "encode_datatype",
        "is_qonnx_datatype",
        "qonnx_datatype_width",
        "resolve_qonnx_datatype_name",
    ),
    "finn.dataflow.model.logical.composition": (
        "NetworkFragment",
        "ParentBoundary",
        "ParentConnection",
        "compose_network",
        "qualify_logical",
        "qualify_network",
        "qualify_region",
    ),
    "finn.dataflow.model.logical.maps": (
        "AffineRankMap",
        "Coordinate",
        "CoordinateSet",
        "ExplicitCoordinateMap",
        "FiniteCoordinateSet",
        "IdentityCoordinateMap",
        "InvalidMapError",
        "MapCapabilityError",
        "MaterializationLimitError",
        "MaterializationRequired",
        "OccurrenceAxis",
        "RectangularDomain",
        "SeparableAffineRequirements",
        "UnboundDomainError",
        "UnsupportedMapEncoding",
        "ValidationCapabilityError",
        "decode_coordinate_map",
        "decode_coordinate_set",
        "decode_requirement_rule",
        "encode_coordinate_map",
        "encode_coordinate_set",
        "encode_requirement_rule",
    ),
    "finn.dataflow.model.logical.region": (
        "BeatSequence",
        "BeatType",
        "DataflowRegion",
        "InputInterface",
        "InternalInput",
        "LogicalSchedule",
        "NumericElementType",
        "Operand",
        "OutputInterface",
        "Port",
        "RegionInput",
        "RegionRefused",
        "ScheduledInputRequirements",
        "ScheduledOutputAvailability",
        "ScheduleLevel",
        "element_width",
        "is_element_type",
    ),
    "finn.dataflow.model.logical.region_profiles": (
        "CanonicalExtentProfile",
        "ProfileCertificationError",
        "ProfileCertificationIssue",
        "direct_output_availability",
        "explicit_beat_sequence",
        "lexicographic_occurrence_to_field",
    ),
    "finn.dataflow.model.logical.region_validation": (
        "RegionValidationIssue",
        "RegionValidationReport",
        "is_structurally_well_formed",
        "validate_region",
    ),
    "finn.dataflow.model.logical.network": (
        "BoundaryContract",
        "ChannelSpec",
        "DataflowNetwork",
        "DirectConnection",
        "Edge",
        "EdgeTransport",
        "FanoutMode",
        "NetworkNode",
        "OrderedChannel",
        "PassCorrespondence",
        "PositionMap",
        "RegionEndpoint",
        "SinkContract",
    ),
    "finn.dataflow.model.logical.network_validation": (
        "NetworkValidationBudget",
        "NetworkValidationIssue",
        "NetworkValidationReport",
        "is_network_structurally_well_formed",
        "validate_network",
    ),
    "finn.dataflow.model.logical.refs": (
        "DataflowOperandRef",
        "NetworkOperandError",
        "RegionInputRef",
        "RegionOutputRef",
        "resolve_input",
        "resolve_output",
    ),
    "finn.dataflow.model.logical.presentation": (
        "boundary_presented_position_set",
        "boundary_presented_positions",
        "edge_presented_position_set",
        "edge_presented_positions",
        "exposing_boundaries",
        "exposing_ports",
        "unpresented_position_set",
        "unpresented_positions",
    ),
    "finn.dataflow.model.logical.results": (
        "CompositionError",
        "ImplementationPath",
        "LogicalResult",
        "NetworkResult",
        "QualifiedChildResult",
        "RegionResult",
    ),
}
_EXPORTS = {name: module for module, names in _EXPORT_GROUPS.items() for name in names}


def __getattr__(name: str) -> object:
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(name)
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))


__all__ = [
    "DatatypeError",
    "QONNXDataType",
    "CompositionError",
    "ImplementationPath",
    "LogicalResult",
    "NetworkFragment",
    "NetworkResult",
    "ParentBoundary",
    "ParentConnection",
    "QualifiedChildResult",
    "RegionResult",
    "canonical_qonnx_datatype",
    "compose_network",
    "decode_datatype",
    "encode_datatype",
    "is_qonnx_datatype",
    "qonnx_datatype_width",
    "qualify_logical",
    "qualify_network",
    "qualify_region",
    "resolve_qonnx_datatype_name",
    "AffineRankMap",
    "BeatSequence",
    "BeatType",
    "Coordinate",
    "CoordinateSet",
    "DataflowRegion",
    "InputInterface",
    "InternalInput",
    "ExplicitCoordinateMap",
    "FiniteCoordinateSet",
    "IdentityCoordinateMap",
    "InvalidMapError",
    "LogicalSchedule",
    "NumericElementType",
    "MapCapabilityError",
    "MaterializationLimitError",
    "MaterializationRequired",
    "OccurrenceAxis",
    "Operand",
    "OutputInterface",
    "Port",
    "RegionInput",
    "RegionRefused",
    "RectangularDomain",
    "ScheduleLevel",
    "ScheduledInputRequirements",
    "ScheduledOutputAvailability",
    "SeparableAffineRequirements",
    "UnboundDomainError",
    "UnsupportedMapEncoding",
    "ValidationCapabilityError",
    "decode_coordinate_map",
    "decode_coordinate_set",
    "decode_requirement_rule",
    "encode_coordinate_map",
    "encode_coordinate_set",
    "encode_requirement_rule",
    "element_width",
    "is_element_type",
    "CanonicalExtentProfile",
    "ProfileCertificationError",
    "ProfileCertificationIssue",
    "direct_output_availability",
    "explicit_beat_sequence",
    "lexicographic_occurrence_to_field",
    "RegionValidationIssue",
    "RegionValidationReport",
    "is_structurally_well_formed",
    "validate_region",
    "BoundaryContract",
    "ChannelSpec",
    "DataflowNetwork",
    "DirectConnection",
    "Edge",
    "EdgeTransport",
    "FanoutMode",
    "NetworkNode",
    "OrderedChannel",
    "PassCorrespondence",
    "PositionMap",
    "RegionEndpoint",
    "SinkContract",
    "NetworkValidationBudget",
    "NetworkValidationIssue",
    "NetworkValidationReport",
    "is_network_structurally_well_formed",
    "validate_network",
    "DataflowOperandRef",
    "NetworkOperandError",
    "RegionInputRef",
    "RegionOutputRef",
    "resolve_input",
    "resolve_output",
    "boundary_presented_position_set",
    "boundary_presented_positions",
    "edge_presented_position_set",
    "edge_presented_positions",
    "exposing_boundaries",
    "exposing_ports",
    "unpresented_position_set",
    "unpresented_positions",
]
