# Copyright (C) 2026, Advanced Micro Devices, Inc.
# SPDX-License-Identifier: BSD-3-Clause

"""C simulation of an HLS leaf: its top compiled by ``g++`` against the HLS headers and
called by a driver FINN writes, with no HLS run (tier T1½).

``c_simulate`` stages the leaf's request (``finn.kernels.artifacts.hls.stage_hls``),
writes the driver from the leaf's ABI alone (each AXIS bus an ``hls::stream`` of
``axis_type``, in the ABI's order, which is the top's argument order), compiles both
against the toolchain's HLS installation (``Toolchain.hls_installation``, as the legacy
flow's cppsim compiles) and runs it: each input's words, with their TLAST where the
bus has one, are read from a file beside the driver; the top is called until every
output has presented the words the caller expects and ``IDLE_CALLS`` calls more, or
until ``IDLE_CALLS`` calls in a row move no word; each output's words, as they came,
are returned.

What it checks is value and sequence: no timing, no stall pattern, no RTL. A free
running top (``ap_ctrl_none``) whose processes each take one step a call is what the
driver calls. It is a check a developer runs before any synthesis, and a separate
evaluation from the RTL's simulation (``finn.core.executors.xsim.rtl``); no gate decides on it.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path

from finn.harness.toolchain import finnlib_root
from finn.kernels.artifacts.abi import Bus, Endpoint, StandardProtocol
from finn.kernels.artifacts.contributions import HlsSource
from finn.kernels.artifacts.hls import TOP, axis_type, include_path, stage_hls
from finn.kernels.artifacts.module import Leaf
from finn.util.toolchain import Toolchain, machine_toolchain, run_process

Words = tuple[Sequence[int], int]
"""A port's words, and the payload bits of each."""

#: Calls of the top that move no word before the driver stops waiting.
IDLE_CALLS = 1000
#: The driver's compile flags beside the include path: FinnLib's own (``hls/hbc.tcl``).
CXXFLAGS = ("-std=c++14", "-O2", "-Wno-unknown-pragmas")


class CSimulationFailed(AssertionError):
    """The top or its driver did not compile, or the driver did not run to its end; the
    message is what the compiler or the driver printed."""


def _streams(leaf: Leaf) -> tuple[Bus, ...]:
    return tuple(
        pin
        for pin in leaf.abi.pins
        if isinstance(pin, Bus) and pin.protocol is StandardProtocol.AXIS
    )


def _width(bus: Bus) -> int:
    return next(member.width for member in bus.signals if member.logical == "tdata")


def _has_last(bus: Bus) -> bool:
    return any(member.logical == "tlast" for member in bus.signals)


def driver(function: str, streams: Sequence[Bus], expected: Mapping[str, int]) -> str:
    """The C++ driver of the top ``function`` over ``streams``: each input read from
    ``<port>.in`` (a hex word and, with TLAST, its last bit, a line each), each output
    written to ``<port>.out`` (a hex word a line); ``expected`` words of each output."""
    types = {bus.name: axis_type(_width(bus), _has_last(bus)) for bus in streams}
    inputs = [bus for bus in streams if bus.endpoint is Endpoint.TARGET]
    outputs = [bus for bus in streams if bus.endpoint is not Endpoint.TARGET]
    lines = [
        "// Generated by finn.harness.hls -- do not edit.",
        "#include <ap_axi_sdata.h>",
        "#include <ap_int.h>",
        "#include <hls_stream.h>",
        "#include <fstream>",
        "#include <iostream>",
        "#include <string>",
        "",
        f"void {function}("
        + ", ".join(f"hls::stream<{types[bus.name]}> &" for bus in streams)
        + ");",
        "",
        "int main() {",
    ]
    for bus in streams:
        lines.append(f"\thls::stream<{types[bus.name]}> {bus.name};")
    for bus in inputs:
        width, last = _width(bus), _has_last(bus)
        lines += [
            "\t{",
            f'\t\tstd::ifstream file("{bus.name}.in");',
            "\t\tstd::string word;",
            "\t\tunsigned last = 0;",
            "\t\twhile(file >> word" + (" >> last" if last else "") + ") {",
            f"\t\t\t{types[bus.name]} beat;",
            f"\t\t\t{'beat.data' if last else 'beat'} = ap_uint<{width}>(word.c_str(), 16);",
            *(["\t\t\tbeat.last = last != 0;"] if last else []),
            f"\t\t\t{bus.name}.write(beat);",
            "\t\t}",
            "\t}",
        ]
    for bus in outputs:
        lines += [
            f'\tstd::ofstream {bus.name}_file("{bus.name}.out");',
            f"\tunsigned long {bus.name}_count = 0;",
        ]
    pending = (
        " || ".join(f"{bus.name}_count < {expected.get(bus.name, 0)}UL" for bus in outputs)
        or "false"
    )
    left = " + ".join(f"{bus.name}.size()" for bus in inputs) or "0"
    lines += [
        "\tunsigned idle = 0, after = 0;",
        f"\twhile(idle < {IDLE_CALLS} && after < {IDLE_CALLS}) {{",
        f"\t\tunsigned long const before = {left};",
        f"\t\t{function}(" + ", ".join(bus.name for bus in streams) + ");",
        f"\t\tbool moved = ({left}) != before;",
    ]
    for bus in outputs:
        value = f"{bus.name}.read()" + (".data" if _has_last(bus) else "")
        lines += [
            f"\t\twhile(!{bus.name}.empty()) {{",
            f"\t\t\t{bus.name}_file << {value}.to_string(16, false) << '\\n';",
            f"\t\t\t{bus.name}_count++;",
            "\t\t\tmoved = true;",
            "\t\t}",
        ]
    lines += [
        "\t\tidle = moved ? 0 : idle + 1;",
        f"\t\tif(!({pending})) after++;",
        "\t}",
        '\tstd::cout << "C SIMULATION DONE" << std::endl;',
        "\treturn 0;",
        "}",
        "",
    ]
    return "\n".join(lines)


def c_simulate(
    leaf: Leaf,
    directory: Path,
    *,
    inputs: Mapping[str, Words],
    lasts: Mapping[str, Sequence[bool]],
    outputs: Mapping[str, int],
    toolchain: Toolchain | None = None,
) -> dict[str, list[int]]:
    """Each output's words as the C simulation of ``leaf``'s top presents them, given each
    input's ``inputs`` and, for a bus with TLAST, each beat's ``lasts``; ``outputs`` is
    the count of words each output must present before the driver stops waiting."""
    requests = [item for item in leaf.sources if isinstance(item, HlsSource)]
    if not requests:
        raise ValueError(f"{leaf.name} is not an HLS leaf: its source is no HLS request")
    request = requests[0]
    streams = _streams(leaf)
    names = {bus.name: bus for bus in streams}
    for name in (*inputs, *outputs):
        if name not in names:
            raise ValueError(f"{leaf.name} has no stream {name}; its streams: {sorted(names)}")
    toolchain = toolchain or machine_toolchain()
    staged = stage_hls(request, directory / "request", roots={"finnlib": finnlib_root()})
    for name, (words, _) in inputs.items():
        bus = names[name]
        flags = lasts.get(name)
        if _has_last(bus) and (flags is None or len(flags) != len(words)):
            raise ValueError(f"{name} has a TLAST: give each of its {len(words)} beats one")
        text = "".join(
            f"{word:x}" + (f" {int(flags[index])}" if _has_last(bus) and flags else "") + "\n"
            for index, word in enumerate(words)
        )
        (directory / f"{name}.in").write_text(text)
    for name, bus in names.items():
        if bus.endpoint is Endpoint.TARGET and name not in inputs:
            (directory / f"{name}.in").write_text("")
    (directory / "driver.cpp").write_text(driver(request.function, streams, outputs))
    include = toolchain.hls_installation() / "include"
    compiled = toolchain.run(
        "g++",
        [
            *CXXFLAGS,
            f"-I{include}",
            *(f"-I{staged.directory / path}" for path in include_path(request)),
            str(staged.directory / TOP),
            "driver.cpp",
            "-o",
            "csim",
        ],
        cwd=directory,
        check=False,
    )
    if compiled.returncode != 0:
        raise CSimulationFailed((compiled.stdout + compiled.stderr).decode(errors="replace"))
    ran = run_process(
        [str(directory / "csim")], env=toolchain.environment, cwd=directory, check=False
    )
    printed = (ran.stdout + ran.stderr).decode(errors="replace")
    if ran.returncode != 0 or "C SIMULATION DONE" not in printed:
        raise CSimulationFailed(printed)
    found = {}
    for name, bus in names.items():
        if bus.endpoint is not Endpoint.TARGET:
            presented = (directory / f"{name}.out").read_text().split()
            found[name] = [int(word, 16) for word in presented]
    return found


__all__ = ["CSimulationFailed", "IDLE_CALLS", "c_simulate"]
