# Copyright (C) 2026, Advanced Micro Devices, Inc.
# SPDX-License-Identifier: BSD-3-Clause

"""Supported authoring API for FINN dataflow design spaces."""

from finn.dataflow._engine import (
    ABSENT,
    AbsenceMode,
    Absent,
    Answer,
    CommitResult,
    Constraint,
    ConstraintAssessment,
    ConstraintSet,
    Decided,
    Decision,
    DecisionDomain,
    DecisionState,
    DependencyKind,
    DependencyRef,
    DependencyView,
    DerivedProperty,
    DesignPoint,
    DesignSpace,
    DesignSpaceSpec,
    Engine,
    EvaluationError,
    EvaluatorSpec,
    Finding,
    FindingKind,
    ItemOutcome,
    ProblemField,
    ProblemSchema,
    ProposalAdoptionMode,
    ProposalAdoptionResult,
    QualifiedPath,
    ReadinessAssessment,
    ReadinessProfile,
    RequestError,
    Unresolved,
    ValidationError,
    ValueSemantics,
    as_object_semantics,
)
from finn.dataflow.design.region import (
    DATAFLOW_NETWORK_SEMANTICS,
    DATAFLOW_REGION_SEMANTICS,
    NETWORK_VALIDATION_REPORT_SEMANTICS,
    REGION_VALIDATION_REPORT_SEMANTICS,
)
from finn.dataflow.network import DataflowNetwork
from finn.dataflow.network_validation import (
    NetworkValidationIssue,
    NetworkValidationReport,
    validate_network,
)
from finn.dataflow.region import DataflowRegion
from finn.dataflow.region_validation import (
    RegionValidationIssue,
    RegionValidationReport,
    validate_region,
)

__all__ = [
    "ABSENT",
    "DATAFLOW_REGION_SEMANTICS",
    "DATAFLOW_NETWORK_SEMANTICS",
    "NETWORK_VALIDATION_REPORT_SEMANTICS",
    "REGION_VALIDATION_REPORT_SEMANTICS",
    "AbsenceMode",
    "Absent",
    "Answer",
    "CommitResult",
    "Constraint",
    "ConstraintAssessment",
    "ConstraintSet",
    "DataflowRegion",
    "DataflowNetwork",
    "Decided",
    "Decision",
    "DecisionDomain",
    "DecisionState",
    "DependencyKind",
    "DependencyRef",
    "DependencyView",
    "DerivedProperty",
    "DesignPoint",
    "DesignSpace",
    "DesignSpaceSpec",
    "Engine",
    "EvaluationError",
    "EvaluatorSpec",
    "Finding",
    "FindingKind",
    "ItemOutcome",
    "NetworkValidationIssue",
    "NetworkValidationReport",
    "ProblemField",
    "ProblemSchema",
    "ProposalAdoptionMode",
    "ProposalAdoptionResult",
    "QualifiedPath",
    "ReadinessAssessment",
    "ReadinessProfile",
    "RegionValidationIssue",
    "RegionValidationReport",
    "RequestError",
    "Unresolved",
    "ValidationError",
    "ValueSemantics",
    "as_object_semantics",
    "validate_region",
    "validate_network",
]
