// Generated by finn.dataflow.designs.physical -- do not edit.
// External-weight decomposed dot product: ReplayBuffer -> DotpAxi.
module finn_mvau_cyclic__e628e25bd87ad3411a63146741f0d61bd99bc3ddc3442eb77cd3f805b02db976 (
    input logic ap_clk,
    input logic ap_clk2x,
    input logic ap_rst_n,
    input logic [7:0] in0_V_tdata,
    output logic in0_V_tready,
    input logic in0_V_tvalid,
    output logic [23:0] out0_V_tdata,
    input logic out0_V_tready,
    output logic out0_V_tvalid
);
    logic n__u_replay__clk;
    logic n__u_replay__rst;
    logic [5:0] n__u_replay__idat;
    logic n__u_replay__irdy;
    logic n__u_replay__ivld;
    logic [5:0] n__u_replay__odat;
    logic n__u_replay__olast;
    logic n__u_replay__ordy;
    logic n__u_replay__ovld;
    logic n__u_compute__ap_clk;
    logic n__u_compute__ap_clk2x;
    logic n__u_compute__ap_rst_n;
    logic [7:0] n__u_compute__s_axis_input_tdata;
    logic n__u_compute__s_axis_input_tlast;
    logic n__u_compute__s_axis_input_tready;
    logic n__u_compute__s_axis_input_tvalid;
    logic [23:0] n__u_compute__s_axis_weights_tdata;
    logic n__u_compute__s_axis_weights_tready;
    logic n__u_compute__s_axis_weights_tvalid;
    logic [23:0] n__u_compute__m_axis_output_tdata;
    logic n__u_compute__m_axis_output_tready;
    logic n__u_compute__m_axis_output_tvalid;
    logic n__u_weights__clk;
    logic n__u_weights__rst;
    logic [17:0] n__u_weights__odat;
    logic n__u_weights__ordy;
    logic n__u_weights__ovld;

    assign n__u_compute__ap_clk = ap_clk;
    assign n__u_compute__ap_clk2x = ap_clk2x;
    assign n__u_compute__ap_rst_n = ap_rst_n;
    assign n__u_replay__clk = ap_clk;
    assign n__u_replay__rst = !ap_rst_n;
    assign n__u_weights__clk = ap_clk;
    assign n__u_weights__rst = !ap_rst_n;
    assign n__u_replay__idat[2:0] = in0_V_tdata[2:0];
    assign n__u_replay__idat[5:3] = in0_V_tdata[5:3];
    assign n__u_replay__ivld = in0_V_tvalid;
    assign in0_V_tready = n__u_replay__irdy;
    assign n__u_compute__s_axis_input_tdata[2:0] = n__u_replay__odat[2:0];
    assign n__u_compute__s_axis_input_tdata[5:3] = n__u_replay__odat[5:3];
    assign n__u_compute__s_axis_input_tvalid = n__u_replay__ovld;
    assign n__u_replay__ordy = n__u_compute__s_axis_input_tready;
    assign n__u_compute__s_axis_input_tlast = n__u_replay__olast;
    assign n__u_compute__s_axis_input_tdata[7:6] = 2'b00;
    assign n__u_compute__s_axis_weights_tdata[2:0] = n__u_weights__odat[2:0];
    assign n__u_compute__s_axis_weights_tdata[5:3] = n__u_weights__odat[5:3];
    assign n__u_compute__s_axis_weights_tdata[8:6] = n__u_weights__odat[8:6];
    assign n__u_compute__s_axis_weights_tdata[11:9] = n__u_weights__odat[11:9];
    assign n__u_compute__s_axis_weights_tdata[14:12] = n__u_weights__odat[14:12];
    assign n__u_compute__s_axis_weights_tdata[17:15] = n__u_weights__odat[17:15];
    assign n__u_compute__s_axis_weights_tvalid = n__u_weights__ovld;
    assign n__u_weights__ordy = n__u_compute__s_axis_weights_tready;
    assign n__u_compute__s_axis_weights_tdata[23:18] = 6'b000000;
    assign out0_V_tdata[7:0] = n__u_compute__m_axis_output_tdata[7:0];
    assign out0_V_tdata[15:8] = n__u_compute__m_axis_output_tdata[15:8];
    assign out0_V_tdata[23:16] = n__u_compute__m_axis_output_tdata[23:16];
    assign out0_V_tvalid = n__u_compute__m_axis_output_tvalid;
    assign n__u_compute__m_axis_output_tready = out0_V_tready;

    replay_buffer #(
        .LEN(3),
        .REP(2),
        .W(6)
    ) u_replay (
        .clk(n__u_replay__clk),
        .rst(n__u_replay__rst),
        .idat(n__u_replay__idat),
        .irdy(n__u_replay__irdy),
        .ivld(n__u_replay__ivld),
        .odat(n__u_replay__odat),
        .olast(n__u_replay__olast),
        .ordy(n__u_replay__ordy),
        .ovld(n__u_replay__ovld),
        .ofin()
    );

    dotp_axi #(
        .ACCU_WIDTH(8),
        .ACTIVATION_BROADCASTING(1),
        .ACTIVATION_WIDTH(3),
        .FORCE_BEHAVIORAL(0),
        .NARROW_WEIGHTS(0),
        .PE(3),
        .PUMPED_COMPUTE(0),
        .SEGMENTLEN(0),
        .SIGNED_ACTIVATIONS(1),
        .SIMD(2),
        .VERSION(2),
        .WEIGHT_WIDTH(3)
    ) u_compute (
        .ap_clk(n__u_compute__ap_clk),
        .ap_clk2x(n__u_compute__ap_clk2x),
        .ap_rst_n(n__u_compute__ap_rst_n),
        .s_axis_input_tdata(n__u_compute__s_axis_input_tdata),
        .s_axis_input_tlast(n__u_compute__s_axis_input_tlast),
        .s_axis_input_tready(n__u_compute__s_axis_input_tready),
        .s_axis_input_tvalid(n__u_compute__s_axis_input_tvalid),
        .s_axis_weights_tdata(n__u_compute__s_axis_weights_tdata),
        .s_axis_weights_tready(n__u_compute__s_axis_weights_tready),
        .s_axis_weights_tvalid(n__u_compute__s_axis_weights_tvalid),
        .m_axis_output_tdata(n__u_compute__m_axis_output_tdata),
        .m_axis_output_tready(n__u_compute__m_axis_output_tready),
        .m_axis_output_tvalid(n__u_compute__m_axis_output_tvalid)
    );

    cyclic_stream #(
        .DEPTH(6),
        .INIT_DATA(108'h15efc551ea234e46e469b9326e4),
        .W(18)
    ) u_weights (
        .clk(n__u_weights__clk),
        .rst(n__u_weights__rst),
        .odat(n__u_weights__odat),
        .ordy(n__u_weights__ordy),
        .ovld(n__u_weights__ovld)
    );
endmodule
