# Copyright (C) 2026, Advanced Micro Devices, Inc.
# SPDX-License-Identifier: BSD-3-Clause

"""Canonical artifact identity and checked-storage API."""

from finn.dataflow.artifacts.identity import (
    COMPOSED_ARTIFACT_SCHEMA_VERSION,
    DEFAULT_BUILDER,
    DEFAULT_VLNV,
    IP_PACKAGE_ARTIFACT_SCHEMA_VERSION,
    KERNEL_ARTIFACT_SCHEMA_VERSION,
    PACKAGED_ARTIFACT_SCHEMA_VERSION,
    SYNTHESIS_ARTIFACT_SCHEMA_VERSION,
    ArtifactIdentityError,
    BuilderIdentity,
    ComposedArtifactIdentity,
    IpPackageArtifactIdentity,
    KernelArtifactIdentity,
    PackagedArtifactIdentity,
    SourceIdentity,
    SynthesisArtifactIdentity,
    TargetIdentity,
    VlnvIdentity,
    composed_artifact_identity,
    content_hash,
    kernel_artifact_identity,
)
from finn.dataflow.artifacts.store import (
    NO_ARTIFACT_STORE,
    ArtifactKey,
    ArtifactStore,
    ArtifactStoreError,
    EmptyArtifactStore,
    StoredArtifact,
    checked_lookup,
)

__all__ = [
    "COMPOSED_ARTIFACT_SCHEMA_VERSION",
    "DEFAULT_BUILDER",
    "DEFAULT_VLNV",
    "IP_PACKAGE_ARTIFACT_SCHEMA_VERSION",
    "KERNEL_ARTIFACT_SCHEMA_VERSION",
    "NO_ARTIFACT_STORE",
    "PACKAGED_ARTIFACT_SCHEMA_VERSION",
    "SYNTHESIS_ARTIFACT_SCHEMA_VERSION",
    "ArtifactIdentityError",
    "ArtifactKey",
    "ArtifactStore",
    "ArtifactStoreError",
    "BuilderIdentity",
    "ComposedArtifactIdentity",
    "EmptyArtifactStore",
    "IpPackageArtifactIdentity",
    "KernelArtifactIdentity",
    "PackagedArtifactIdentity",
    "SourceIdentity",
    "StoredArtifact",
    "SynthesisArtifactIdentity",
    "TargetIdentity",
    "VlnvIdentity",
    "checked_lookup",
    "composed_artifact_identity",
    "content_hash",
    "kernel_artifact_identity",
]
