# Copyright (C) 2026, Advanced Micro Devices, Inc.
# SPDX-License-Identifier: BSD-3-Clause

"""A QONNX CustomOp and the root Space of its implementation choices.

Source and build facts have one authority: the root ProblemSnapshot. Private
occurrence state retains only copied node bytes, scope addressing and output
observations. Queries use that frozen occurrence; rebind explicitly reads the
live model. Native attributes persist committed reachable Decisions only.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from types import MappingProxyType
from typing import TYPE_CHECKING, Any, ClassVar, cast

from qonnx.custom_op.base import CustomOp  # type: ignore[import-not-found]

from finn.dataflow._engine import Answer, Decided, Unresolved
from finn.dataflow.space.declarations import (
    AuthoringError,
    Constraint as DeclaredConstraint,
    ConstraintGroup,
    OccurrenceContext,
    Problem,
    Space,
)
from finn.dataflow.space.occurrence import (
    ProjectionAssessment,
    occurrence_answer_at,
    occurrence_persistable,
)
from finn.dataflow.model.network import DataflowNetwork
from finn.dataflow.model.refs import DataflowOperandRef, NetworkOperandError
from finn.dataflow.ops.mapping import OperandMapping, _derive_operand_mappings
from finn.dataflow.ops.native import (
    AttributeCodec,
    SCOPE_ID_ATTRIBUTE,
    FINGERPRINT_ATTRIBUTE,
    SCHEMA_VERSION_ATTRIBUTE,
    RESERVED_ATTRIBUTES,
    NativeAttribute,
    choice_schema,
    compiled_choice_schema,
    hydrate,
    serialize_choices,
)
from finn.dataflow.ops.schema import (
    SOURCE_DECLARATION_TYPES,
    Attribute,
    BuildFact,
    DatatypeAttribute,
    SourceDeclaration,
    OpInput,
    OpOutput,
    attribute_name,
    lower_source_schema,
)
from finn.dataflow.ops.source import SourceError, SourceNode, SourceOperand, read_source_node
from finn.dataflow.ops.reconstruction import bind_operations, source_analysis

if TYPE_CHECKING:
    from onnx import NodeProto  # type: ignore[import-not-found]

DATAFLOW_DOMAIN = "finn.custom_op.dataflow"


class DataflowOpError(ValueError):
    def __init__(self, message: str, findings: Sequence[object] = ()) -> None:
        super().__init__(message)
        self.findings = tuple(findings)


@dataclass(frozen=True, slots=True)
class _BoundNode:
    node_bytes: bytes
    scope_id: str
    opset_version: int
    outputs: tuple[SourceOperand, ...]

    def materialize(self) -> Any:
        from onnx import NodeProto  # noqa: PLC0415

        node = NodeProto()
        node.ParseFromString(self.node_bytes)
        return node


def source_declarations(
    operation_type: type[DataflowOp],
) -> tuple[tuple[str, SourceDeclaration], ...]:
    ordered: dict[str, SourceDeclaration] = {}
    for base in reversed(operation_type.__mro__):
        if not isinstance(base, type) or not issubclass(base, Space):
            continue
        for name, value in vars(base).items():
            if isinstance(value, SOURCE_DECLARATION_TYPES):
                ordered[name] = cast(SourceDeclaration, value)
    return tuple(ordered.items())


class DataflowOp(Space, CustomOp):  # type: ignore[misc]
    family: ClassVar[str] = ""
    family_version: ClassVar[str] = "1"
    schema_version: ClassVar[int] = 2
    root_namespace: ClassVar[str] = "op"
    wants_model: ClassVar[bool] = True
    source_accepts: ClassVar[Any] = ConstraintGroup()

    @classmethod
    def _finalize_compilation(cls, compiled: object) -> object:
        _check_authoring(cls)
        compiled_choice_schema(cls, compiled)
        return compiled

    def __init_subclass__(cls, **kwargs: object) -> None:
        declarations = dict(vars(cls))
        schema = {
            name: cast(SourceDeclaration, value)
            for name, value in declarations.items()
            if isinstance(value, SOURCE_DECLARATION_TYPES)
        }
        _check_indices(cls, schema)
        _check_constraints_are_classified(cls, declarations)
        _check_attribute_names(cls)
        for name, member in lower_source_schema(cls, schema).items():
            if name in declarations:
                raise AuthoringError(
                    f"{cls.__name__}.{name} collides with a member generated by the source schema"
                )
            setattr(cls, name, member)
        super().__init_subclass__(**kwargs)

    def __init__(self, onnx_node: NodeProto, onnx_opset_version: int = 1) -> None:
        CustomOp.__init__(self, onnx_node, onnx_opset_version)
        self._model: Any | None = None
        self._bound: _BoundNode | None = None
        _check_authoring(type(self))

    @classmethod
    def _allocate_bound(cls, context: OccurrenceContext, state: _BoundNode) -> DataflowOp:
        del context
        instance = object.__new__(cls)
        instance.onnx_node = state.materialize()
        instance.onnx_opset_version = state.opset_version
        instance._model = None
        instance._bound = state
        return instance

    def bind(self, model: Any, build: Any) -> Any:
        """Reconstruct this operation through the model-level pass owner.

        For several operations use bind_operations(model, build), or wrap the
        caller's loop in source_analysis(model), to share its one bulk result.
        """
        return bind_operations(model, build, operations=(self,))[0]

    def _build_values(self, build: Any) -> Mapping[Problem[Any], object]:
        return MappingProxyType(
            {
                cast("Problem[Any]", decl): value
                for name, decl in source_declarations(type(self))
                if isinstance(decl, BuildFact)
                if (value := _build_value(type(self), name, decl, build)) is not None
            }
        )

    def _frozen_build_values(self) -> Mapping[Problem[Any], object]:
        return MappingProxyType(
            {
                problem: value
                for problem, value in self.problem_snapshot.items()
                if isinstance(problem, BuildFact)
            }
        )

    def _bind_with(
        self,
        model: Any,
        facts: Mapping[Problem[Any], object],
        summaries: Mapping[str, Any],
        *,
        recorded: bool = True,
    ) -> Any:
        node = self._live_node(model)
        source = self._read_source(model, node, summaries)
        state = _BoundNode(
            node.SerializeToString(deterministic=True),
            self.recorded_scope_id() or "",
            int(self.onnx_opset_version),
            source.outputs,
        )
        values = dict(facts)
        for name, declaration in source_declarations(type(self)):
            if isinstance(declaration, OpInput):
                if source.has(name):
                    operand = source.operand(name)
                    values[declaration] = operand
                    if operand.tensor in summaries:
                        values[declaration.value_summary] = summaries[operand.tensor]
            elif isinstance(declaration, (Attribute, DatatypeAttribute)):
                values[declaration] = source.attributes[name]
        root = type(self)._start_frozen(values, state)
        return hydrate(root) if recorded else root

    @classmethod
    def _start_frozen(cls, values: Mapping[Problem[Any], object], state: _BoundNode) -> Any:
        root = cls.start(
            values,
            namespace=cls.root_namespace,
            root_factory=lambda context: cls._allocate_bound(context, state),
        )
        return root

    def rebind(self, model: Any, build: Any = None) -> Any:
        """Read current source facts by scope id; omitted build reuses root Problems."""
        from finn.dataflow.ops.persistence import find_node  # noqa: PLC0415

        state = self._bound_node()
        fresh = type(self)(find_node(model, state.scope_id), state.opset_version)
        with source_analysis(model) as summaries:
            facts = self._frozen_build_values() if build is None else self._build_values(build)
            return fresh._bind_with(model, facts, summaries)

    def reconstruct(self, problem: Any = None, **kwargs: Any) -> Any:
        """Drop choices while retaining this occurrence's existing ProblemSnapshot."""
        if problem is not None:
            raise DataflowOpError(
                "a DataflowOp reconstructs from its frozen source, not from an arbitrary "
                "problem mapping; use rebind(model, build)"
            )
        expected = kwargs.get("expected_problem_fingerprint")
        if expected is not None and expected != self.problem_fingerprint:
            raise DataflowOpError(
                f"this operation's problem is {self.problem_fingerprint}, not {expected}"
            )
        return type(self)._start_frozen(self.problem_snapshot, self._bound_node())

    def is_stale(self, problem: Any = None) -> bool:
        if problem is None:
            raise DataflowOpError(
                "call is_stale((model, build)) or compare rebind(...).problem_fingerprint"
            )
        model, build = problem
        with source_analysis(model) as summaries:
            root = self._bind_with(model, self._build_values(build), summaries, recorded=False)
        return bool(root.problem_fingerprint != self.problem_fingerprint)

    def _bound_node(self) -> _BoundNode:
        if self._bound is None:
            raise DataflowOpError(f"{type(self).__name__} is not bound; call bind(model, build)")
        return self._bound

    @property
    def is_bound(self) -> bool:
        return self._bound is not None

    @property
    def source(self) -> SourceNode:
        """Present root Problems and frozen output observations as a source reading."""
        state = self._bound_node()
        node = state.materialize()
        inputs = []
        attributes = {}
        for name, declaration in source_declarations(type(self)):
            if isinstance(declaration, OpInput) and declaration in self.problem_snapshot:
                inputs.append(cast(SourceOperand, self.problem_snapshot[declaration]))
            elif isinstance(declaration, (Attribute, DatatypeAttribute)):
                attributes[name] = self.problem_snapshot[declaration]
        return SourceNode(
            node.name,
            node.op_type,
            node.domain,
            tuple(inputs),
            state.outputs,
            MappingProxyType(attributes),
        )

    def _live_node(self, model: Any) -> Any:
        from finn.dataflow.ops.persistence import find_node  # noqa: PLC0415

        scope = self.recorded_scope_id()
        if scope is None:
            raise SourceError(
                f"{self.onnx_node.name!r} has no dataflow scope id; "
                "run AssignDataflowScopeIds first"
            )
        try:
            return find_node(model, scope)
        except DataflowOpError as error:
            raise SourceError(str(error)) from error

    def _read_source(self, model: Any, node: Any, summaries: Mapping[str, Any]) -> SourceNode:
        inputs: list[tuple[int, str]] = []
        outputs: list[tuple[int, str]] = []
        optional = []
        attributes = {}
        for name, declaration in source_declarations(type(self)):
            if isinstance(declaration, (OpInput, OpOutput)):
                (outputs if declaration.output else inputs).append((declaration.index, name))
                if isinstance(declaration, OpInput) and declaration.optional:
                    optional.append(name)
            elif isinstance(declaration, DatatypeAttribute):
                attributes[name] = _datatype_attribute(node, name, declaration)
            elif isinstance(declaration, Attribute):
                attributes[name] = _plain_attribute(node, name, declaration)
        return read_source_node(
            model,
            node,
            inputs=_positional(inputs),
            outputs=_positional(outputs),
            optional_inputs=optional,
            attributes=attributes,
            summaries=summaries,
        )

    def read_source(self, model: Any) -> SourceNode:
        with source_analysis(model) as summaries:
            return self._read_source(model, self._live_node(model), summaries)

    def source_snapshot(self, model: Any) -> SourceNode:
        return self.source if self.is_bound else self.read_source(model)

    def attached_source(self) -> SourceNode:
        if self.is_bound:
            return self.source
        if self._model is None:
            raise DataflowOpError(f"{type(self).__name__} has no model attached")
        return self.read_source(self._model)

    def attach_model(self, model: Any) -> DataflowOp:
        if not self.is_bound:
            self._model = model
        return self

    def set_nodeattr(self, name: str, value: Any) -> None:
        if self.is_bound:
            raise DataflowOpError(
                f"a bound occurrence is a frozen snapshot; use graph_effects() to set {name!r}"
            )
        CustomOp.set_nodeattr(self, name, value)

    def get_nodeattr_types(self) -> Mapping[str, tuple[str, bool, object]]:
        result: dict[str, tuple[str, bool, object]] = {
            SCOPE_ID_ATTRIBUTE: ("s", False, ""),
            FINGERPRINT_ATTRIBUTE: ("s", False, ""),
            SCHEMA_VERSION_ATTRIBUTE: ("i", False, 0),
        }
        for name, declaration in source_declarations(type(self)):
            if isinstance(declaration, DatatypeAttribute):
                result[attribute_name(name, declaration)] = (
                    "s",
                    declaration.default is None,
                    declaration.default or "",
                )
            elif isinstance(declaration, Attribute):
                kind = (
                    "s"
                    if declaration.value_type is str
                    else "f"
                    if declaration.value_type is float
                    else "i"
                )
                result[attribute_name(name, declaration)] = (kind, False, declaration.default)
        if self.is_bound:
            for name, attribute in serialize_choices(self).items():
                result[name] = (attribute.kind, False, attribute.value)
        return result

    def make_shape_compatible_op(self, model: Any) -> Any:
        expected = self.expected_for(self.source_snapshot(model))
        declaration = next(
            (
                (name, decl)
                for name, decl in source_declarations(type(self))
                if isinstance(decl, OpOutput) and decl.index == 0
            ),
            None,
        )
        entry = expected.get(declaration[0]) if declaration else None
        if entry is None or entry[0] is None:
            raise DataflowOpError(f"{self.onnx_node.name} cannot state a shape-compatible op")
        from onnx import helper  # noqa: PLC0415

        return helper.make_node(
            "RandomNormal", [], [self.onnx_node.output[0]], shape=list(entry[0])
        )

    def infer_node_datatype(self, model: Any) -> None:
        source = self.source_snapshot(model)
        for name, (_, datatype) in self.expected_for(source).items():
            if datatype is not None and source.has(name):
                model.set_tensor_datatype(source.operand(name).tensor, datatype)

    def assess_source(self, model: Any = None) -> Any:
        if self.is_bound:
            return self.assess(type(self).source_accepts)
        graph_model = self._model if model is None else model
        if graph_model is None:
            raise DataflowOpError(f"{type(self).__name__} has no model attached")
        with source_analysis(graph_model) as summaries:
            root = self._bind_with(graph_model, {}, summaries, recorded=False)
        return root.assess(type(self).source_accepts)

    def verify_node(self) -> list[str]:
        assessment = self.assess_source()
        if assessment.verdict is True:
            return []
        return [
            finding.message
            for answer in assessment.answers.values()
            for finding in getattr(answer, "findings", ())
        ]

    def execute_node(self, context: Any, graph: Any) -> None:
        raise NotImplementedError(f"{type(self).__name__} does not execute its source semantics")

    def recorded_scope_id(self) -> str | None:
        if self._bound is not None:
            return self._bound.scope_id
        return _string_attribute(self.onnx_node, SCOPE_ID_ATTRIBUTE) or None

    @property
    def dataflow(self) -> ProjectionAssessment[DataflowNetwork]:
        return _root_projection(self)

    @property
    def network(self) -> Answer[DataflowNetwork]:
        return self.dataflow.accepted_answer

    def selected_dataflow(self) -> ProjectionAssessment[DataflowNetwork] | None:
        raise NotImplementedError(f"{type(self).__name__} does not route to a Design")

    def operand_references(
        self, network: DataflowNetwork
    ) -> Mapping[str, tuple[DataflowOperandRef, ...]]:
        """Source members to qualified targets, authored by this operation.

        network has passed the Design dataflow projection. This method supplies
        correspondence only; exposure and position coverage are derived.
        """
        raise NotImplementedError(f"{type(self).__name__} does not declare operand references")

    @property
    def operand_mapping(self) -> Answer[tuple[OperandMapping, ...]]:
        answer = self.network
        if not isinstance(answer, Decided):
            return cast("Answer[tuple[OperandMapping, ...]]", answer)
        references = self.operand_references(answer.value)
        declarations = {
            name: decl
            for name, decl in source_declarations(type(self))
            if isinstance(decl, (OpInput, OpOutput))
        }
        source = self.source
        expected = {item.id for item in (*source.inputs, *source.outputs)}
        if set(references) != expected or any(not refs for refs in references.values()):
            raise NetworkOperandError("operand references must cover every present source operand")
        for name, refs in references.items():
            semantic_id = declarations[name].operand
            if semantic_id and any(ref.operand_id != semantic_id for ref in refs):
                raise NetworkOperandError(f"{name!r} declares semantic operand {semantic_id!r}")
        return Decided(
            _derive_operand_mappings(
                answer.value,
                source,
                references,
                {name: decl.correspondence for name, decl in declarations.items()},
            )
        )

    def expected_for(self, source: SourceNode) -> Mapping[str, tuple[tuple[int, ...] | None, Any]]:
        del source
        return {}

    def expected_outputs(self) -> Mapping[str, tuple[tuple[int, ...] | None, Any]]:
        return self.expected_for(self.source)

    def reconciliation(self) -> tuple[str, ...]:
        differences = []
        source = self.source
        for name, (shape, datatype) in self.expected_outputs().items():
            if not source.has(name):
                continue
            observed = source.operand(name)
            if shape is not None and (not observed.annotated or observed.shape != tuple(shape)):
                differences.append(
                    f"{name}: the graph annotates shape {observed.shape}, "
                    f"this operation produces {shape}"
                )
            if datatype is not None and observed.datatype != datatype:
                differences.append(
                    f"{name}: the graph annotates datatype {observed.datatype.name}, "
                    f"this operation produces {datatype.name}"
                )
        return tuple(differences)

    def graph_effects(self, *, require: Any = None) -> Any:
        """Plan native attribute replacement and output repairs without writing."""
        from finn.dataflow.ops.persistence import CommitmentStage, GraphEffects, check_commitment  # noqa: PLC0415

        state = self._bound_node()
        stage = CommitmentStage.DATAFLOW if require is None else require
        check_commitment({CommitmentStage.DATAFLOW: self.dataflow}, stage)
        schema = choice_schema(self)
        written = serialize_choices(self)
        written.update(
            {
                SCOPE_ID_ATTRIBUTE: NativeAttribute("s", state.scope_id),
                FINGERPRINT_ATTRIBUTE: NativeAttribute("s", self.problem_fingerprint),
                SCHEMA_VERSION_ATTRIBUTE: NativeAttribute("i", self.schema_version),
            }
        )
        names = {item.name for item in schema} | RESERVED_ATTRIBUTES
        node = state.materialize()
        current = {item.name: item.SerializeToString(deterministic=True) for item in node.attribute}
        source = self.source
        return GraphEffects(
            scope_id=state.scope_id,
            commitment_stage=stage,
            expected_source_fingerprint=self.problem_fingerprint,
            expected_attributes=MappingProxyType({name: current.get(name) for name in names}),
            remove_attributes=tuple(sorted(names - written.keys())),
            set_attributes=MappingProxyType(written),
            tensor_datatypes=MappingProxyType(
                {
                    source.operand(name).tensor: datatype
                    for name, (_, datatype) in self.expected_outputs().items()
                    if datatype is not None and source.has(name)
                }
            ),
            tensor_shapes=MappingProxyType(
                {
                    source.operand(name).tensor: tuple(shape)
                    for name, (shape, _) in self.expected_outputs().items()
                    if shape is not None and source.has(name)
                }
            ),
            operation_type=type(self),
            opset_version=state.opset_version,
            build_facts=self._frozen_build_values(),
            expected_operator=(node.domain, node.op_type),
            expected_outputs=tuple(node.output),
            invalidates=("dataflow.implementation",)
            if any(
                current.get(name) != value.proto(name).SerializeToString(deterministic=True)
                for name, value in written.items()
            )
            or names - written.keys() & current.keys()
            else (),
        )

    def commit(self, model: Any, build: Any = None, *, require: Any = None) -> Any:
        from finn.dataflow.ops.persistence import apply_graph_effects  # noqa: PLC0415

        if build is not None:
            offered = self._build_values(build)
            frozen = self._frozen_build_values()
            if dict(offered) != dict(frozen):
                names = [
                    name
                    for name, declaration in source_declarations(type(self))
                    if isinstance(declaration, BuildFact)
                    and offered.get(declaration) != frozen.get(declaration)
                ]
                raise DataflowOpError(
                    f"build facts differ at commit ({', '.join(names)}); rebind first"
                )
        apply_graph_effects(model, self.graph_effects(require=require))
        return self.rebind(model)

    def recorded(self) -> Mapping[str, object]:
        if not self.is_bound:
            raise DataflowOpError(
                "operation is not bound; call bind(model, build) or inspect native attributes "
                "with read_attributes(node)"
            )
        return MappingProxyType(
            {
                choice.path: answer.value
                for choice in occurrence_persistable(self)
                if isinstance(answer := occurrence_answer_at(self, choice.reference), Decided)
            }
        )


def _root_projection(operation: DataflowOp) -> ProjectionAssessment[DataflowNetwork]:
    """Combine the operation's own source semantics with its selected Design's.

    The reduction is the engine's, not a second one: readiness and constraint
    assessments are concatenated and handed to the same
    ``_reduce_projection`` ordering every other projection uses, so
    "Unresolved dominates, then absence, then refusal" cannot come to mean two
    slightly different things in two places.
    """

    from finn.dataflow.space.occurrence import (  # noqa: PLC0415 - see graph_effects
        combine_assessments,
    )

    source = operation.assess(type(operation).source_accepts)
    selected = operation.selected_dataflow()
    if selected is None:
        return cast(
            "ProjectionAssessment[DataflowNetwork]",
            combine_assessments("dataflow", (source,), None),
        )
    return cast(
        "ProjectionAssessment[DataflowNetwork]",
        combine_assessments("dataflow", (source, *selected.constraints), selected),
    )


def _check_indices(operation_type: type, schema: Mapping[str, Any]) -> None:
    """Refuse a sparse or repeated operand schema where it is written.

    An index is an *index*, not a hint about ordering.  Sorting by it and
    handing the names to a positional reader silently reinterprets
    ``OpInput(index=3)`` as "the next one", which is exactly wrong the
    moment an operation declares a sparse or out-of-order schema -- and that is
    what optional operands make ordinary.
    """

    for what, wanted in (("input", False), ("output", True)):
        indices = sorted(
            declaration.index
            for declaration in schema.values()
            if isinstance(declaration, (OpInput, OpOutput)) and declaration.output is wanted
        )
        if indices != list(range(len(indices))):
            raise AuthoringError(
                f"{operation_type.__name__} declares {what} indices {indices}; they must be "
                "unique and contiguous from zero, because an ONNX operand list is positional"
            )


def _check_constraints_are_classified(
    operation_type: type[DataflowOp], declarations: Mapping[str, object]
) -> None:
    """Every authored operation Constraint gates the source semantics, explicitly.

    The rule the Kernel and Design layers already state, for the reason that
    applies identically here: an operation has exactly one group, and a
    constraint outside it is compiled, evaluated, and consulted by nothing --
    so an operation would silently stop refusing what its author wrote a
    refusal for.  ``source_accepts`` is small enough that omitting a name from
    it is easy and invisible, which is why it is checked rather than trusted.

    An *output* observation deliberately has no place here: it is a
    reconciliation difference, not a verdict, and a constraint is not how it is
    reported.
    """

    group = declarations.get("source_accepts")
    if group is not None and not isinstance(group, ConstraintGroup):
        raise AuthoringError(
            f"{operation_type.__name__}.source_accepts is a {type(group).__name__}; it names "
            "one ConstraintGroup of the constraints that gate this operation's own semantics"
        )
    grouped = (
        {id(item) for item in group.constraints} if isinstance(group, ConstraintGroup) else set()
    )
    ungrouped = sorted(
        name
        for name, declaration in declarations.items()
        if isinstance(declaration, DeclaredConstraint) and id(declaration) not in grouped
    )
    if ungrouped:
        raise AuthoringError(
            f"{operation_type.__name__} declares Constraint {ungrouped[0]!r} outside "
            "source_accepts; an operation says which projection each of its constraints "
            "gates, because a constraint in no group refuses nothing"
        )


def _positional(declared: list[tuple[int, str]]) -> tuple[str, ...]:
    return tuple(name for _index, name in sorted(declared))


def _check_authoring(operation_type: type[DataflowOp]) -> None:
    if type(operation_type.schema_version) is not int or operation_type.schema_version < 1:
        raise AuthoringError("a DataflowOp schema_version must be a positive integer")
    if not operation_type.family:
        raise AuthoringError(f"{operation_type.__name__} must declare a non-empty family")
    _check_attribute_names(operation_type)


def _check_attribute_names(operation_type: type[DataflowOp]) -> None:
    """Refuse two members reading one node attribute, and any the layer owns.

    Checked on the *graph* name, which is the one that can collide: two members
    cannot share a Python name, but two members can name one ONNX attribute --
    which is newly possible now that ``onnx=`` separates the two -- and one of
    them would silently win.
    """

    graph_names: dict[str, str] = {}
    for member_name, declaration in source_declarations(operation_type):
        if not isinstance(declaration, (Attribute, DatatypeAttribute)):
            continue
        name = attribute_name(member_name, declaration)
        if name in RESERVED_ATTRIBUTES:
            raise AuthoringError(
                f"{operation_type.__name__} declares source attribute {name!r}, which the "
                "dataflow layer owns"
            )
        if name in graph_names:
            raise AuthoringError(
                f"{operation_type.__name__}.{member_name} and "
                f"{operation_type.__name__}.{graph_names[name]} both read the node attribute "
                f"{name!r}; one graph attribute is one source fact"
            )
        graph_names[name] = member_name


def _raw_attribute(node: Any, name: str) -> Any | None:
    attribute = _attribute(node, name)
    if attribute is None:
        return None
    if attribute.type == attribute.STRING:
        return attribute.s
    if attribute.type == attribute.FLOAT:
        return attribute.f
    if attribute.type == attribute.INT:
        return attribute.i
    raise SourceError(f"{node.name} has an unsupported kind for source attribute {name!r}")


def _datatype_attribute(node: Any, member_name: str, declaration: DatatypeAttribute) -> object:
    from finn.dataflow.model.datatypes import canonical_qonnx_datatype  # noqa: PLC0415 - cycle
    from qonnx.core.datatype import DataType  # type: ignore[import-not-found] # noqa: PLC0415

    raw = _raw_attribute(node, attribute_name(member_name, declaration))
    name = declaration.default if raw is None else raw
    if name is None:
        raise SourceError(
            f"{node.name} requires source attribute {attribute_name(member_name, declaration)!r}"
        )
    text = name.decode("utf-8") if isinstance(name, bytes) else str(name)
    return canonical_qonnx_datatype(DataType[text])


def _plain_attribute(node: Any, member_name: str, declaration: Attribute) -> object:
    raw = _raw_attribute(node, attribute_name(member_name, declaration))
    if raw is None:
        return declaration.default
    if declaration.value_type is str:
        return raw.decode("utf-8") if isinstance(raw, bytes) else str(raw)
    return declaration.value_type(raw)


def _build_value(
    operation_type: type[DataflowOp],
    member_name: str,
    declaration: BuildFact,
    build: Any,
) -> object:
    """One build scalar, or a refusal naming what the configuration owes.

    ``build_required`` and not ``Problem.required``: the Problem is always
    absence-tolerant so that an occurrence can start with no build at all, and
    reading that flag here would mean every build fact is optional -- a missing
    clock period would silently become ``None`` and travel into a Design as an
    unresolved Input, reported as a folding problem rather than a
    configuration one.

    A ``None`` result is checked as strictly as a raising accessor: a
    configuration that supplies the attribute and sets it to nothing has
    supplied nothing.
    """

    try:
        value = declaration.accessor(build)
    except (AttributeError, KeyError, TypeError) as error:
        if declaration.build_required and declaration.default is None:
            raise DataflowOpError(
                f"{operation_type.__name__} needs build fact {member_name!r}, and this "
                f"build configuration does not supply it: {error}"
            ) from error
        return declaration.default
    if value is None:
        if declaration.build_required and declaration.default is None:
            raise DataflowOpError(
                f"{operation_type.__name__} needs build fact {member_name!r}, and this "
                "build configuration supplies nothing for it"
            )
        return declaration.default
    return value


def _attribute(node: Any, name: str) -> Any | None:
    for attribute in node.attribute:
        if attribute.name == name:
            return attribute
    return None


def _string_attribute(node: Any, name: str) -> str:
    attribute = _attribute(node, name)
    if attribute is None:
        return ""
    value = attribute.s
    return value.decode("utf-8") if isinstance(value, bytes) else str(value)


def unresolved_reason(answer: Answer[Any]) -> str:
    """A short account of why a projection is not available, for a message."""

    if isinstance(answer, Decided):
        return "decided"
    findings = getattr(answer, "findings", ())
    kind = "unresolved" if isinstance(answer, Unresolved) else "absent"
    codes = ", ".join(sorted({finding.code for finding in findings})) or "no findings"
    return f"{kind}: {codes}"


__all__ = [
    "DATAFLOW_DOMAIN",
    "FINGERPRINT_ATTRIBUTE",
    "RESERVED_ATTRIBUTES",
    "SCOPE_ID_ATTRIBUTE",
    "SCHEMA_VERSION_ATTRIBUTE",
    "AttributeCodec",
    "DataflowOp",
    "DataflowOpError",
    "source_declarations",
    "unresolved_reason",
]
