"""
Base Code Generator - Shared Infrastructure for Unified FINN Code Generation

This module provides the abstract base class that defines the common interface
and shared functionality for both HLS and RTL code generators.
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Any, Optional
import os
from pathlib import Path

from .template_engine import TemplateEngine
from .file_manager import FileManager
from .library_resolver import LibraryResolver


class BaseCodeGenerator(ABC):
    """
    Abstract base class for unified code generation.
    
    Adopts RTL's successful operation-driven pattern where each operation
    controls its own generation process, while providing shared infrastructure
    for template processing, file management, and library resolution.
    """
    
    def __init__(self, operation):
        """
        Initialize the code generator with an operation instance.
        
        Args:
            operation: HWCustomOp instance that needs code generation
        """
        self.operation = operation
        self.template_engine = TemplateEngine()
        self.file_manager = FileManager()
        self.library_resolver = LibraryResolver()
        
    @abstractmethod
    def get_template_name(self) -> str:
        """
        Get the template name for this operation.
        
        Each generator must specify which template to use for code generation.
        This enables operation-specific templates rather than mega-templates.
        
        Returns:
            Template filename/path for this operation
        """
        pass
    
    @abstractmethod
    def prepare_context(self, model, fpgapart: str, clk: str) -> Dict[str, Any]:
        """
        Prepare the template context for code generation.
        
        Each generator must implement operation-specific context preparation.
        This replaces the rigid prepare_codegen_* methods with flexible context.
        
        Args:
            model: FINN model containing the operation
            fpgapart: Target FPGA part string
            clk: Clock specification
            
        Returns:
            Dictionary containing template variables and values
        """
        pass
    
    def generate_code(self, model, fpgapart: str, clk: str) -> str:
        """
        Generate code for this operation using the unified framework.
        
        This method implements the shared generation logic:
        1. Prepare operation-specific context
        2. Get operation-specific template
        3. Render template with context
        4. Return generated code
        
        Args:
            model: FINN model containing the operation
            fpgapart: Target FPGA part string
            clk: Clock specification
            
        Returns:
            Generated code as string
        """
        # Prepare operation-specific context
        context = self.prepare_context(model, fpgapart, clk)
        
        # Add common context items available to all templates
        context.update(self._get_common_context(model, fpgapart, clk))
        
        # Get operation-specific template
        template_name = self.get_template_name()
        
        # Render template with context
        return self.template_engine.render(template_name, context)
    
    def _get_common_context(self, model, fpgapart: str, clk: str) -> Dict[str, Any]:
        """
        Get common context items available to all templates.
        
        Args:
            model: FINN model containing the operation
            fpgapart: Target FPGA part string
            clk: Clock specification
            
        Returns:
            Dictionary with common template variables
        """
        return {
            'fpgapart': fpgapart,
            'clk': clk,
            'operation': self.operation,
            'node': self.operation.onnx_node,
            'op_type': self.operation.onnx_node.op_type,
            'node_name': self.operation.onnx_node.name,
            'includes': self.get_include_files(),
            'libraries': self.get_library_dependencies(),
        }
    
    def get_include_files(self) -> List[str]:
        """
        Get include files needed for this operation.
        
        Uses the library resolver to dynamically determine includes
        based on operation requirements.
        
        Returns:
            List of include file paths
        """
        return self.library_resolver.resolve_includes(self.operation)
    
    def get_library_dependencies(self) -> List[str]:
        """
        Get library dependencies for this operation.
        
        Returns:
            List of library dependency specifications
        """
        return self.library_resolver.resolve_libraries(self.operation)
    
    @abstractmethod
    def get_generated_files(self, code_gen_dir: str) -> List[str]:
        """
        Get list of files that will be generated by this generator.
        
        Each generator must specify what files it will create.
        This enables proper file management and dependency tracking.
        
        Args:
            code_gen_dir: Directory where files will be generated
            
        Returns:
            List of file paths that will be generated
        """
        pass
    
    def write_generated_files(self, model, fpgapart: str, clk: str, code_gen_dir: str) -> List[str]:
        """
        Generate and write all files for this operation.
        
        This method coordinates the complete file generation process:
        1. Ensure output directory exists
        2. Generate code content
        3. Write files using file manager
        4. Return list of created files
        
        Args:
            model: FINN model containing the operation
            fpgapart: Target FPGA part string
            clk: Clock specification
            code_gen_dir: Directory where files should be written
            
        Returns:
            List of file paths that were created
        """
        # Ensure output directory exists
        self.file_manager.ensure_directory(code_gen_dir)
        
        # Generate code content
        generated_code = self.generate_code(model, fpgapart, clk)
        
        # Get expected output files
        output_files = self.get_generated_files(code_gen_dir)
        
        # Write main generated file (typically the first one)
        if output_files:
            main_file = output_files[0]
            self.file_manager.write_file(main_file, generated_code)
            
        # Subclasses can override this method to handle multiple files
        return output_files
    
    def validate_operation(self) -> bool:
        """
        Validate that this operation can be handled by this generator.
        
        Returns:
            True if operation is supported, False otherwise
        """
        # Basic validation - subclasses can override for specific checks
        return self.operation is not None and hasattr(self.operation, 'onnx_node')