############################################################################
# Copyright (C) 2025, Advanced Micro Devices, Inc.
# All rights reserved.
# Portions of this content consist of AI generated content.
#
# SPDX-License-Identifier: BSD-3-Clause
############################################################################

"""``origin`` — provenance on generated entries (engine hone Task 6.2).

Most entries in a compiled space are not written by anyone: they are generated by the
tiling engine, the pool combinator or the constraint compiler. When one appears in an error
the name alone does not say which mechanism produced it, so tracing means knowing the
generators well enough to guess — the 7-hop dtype trace the hone measured.

``origin`` is metadata only. Nothing resolves, orders or gates on it, which is what keeps it
from becoming a second home for a fact the deps already carry.
"""

import pytest

from finn.kernels.engine.design_space import DesignSpace
from finn.kernels.engine.derived import Derived
from finn.kernels.engine.resolve import resolve
from finn.kernels.engine.context import Context
from finn.kernels.engine.point import Illegal
from finn.kernels.engine.predicate import Predicate


@pytest.fixture(scope="module")
def mvau_space():
    from finn.kernels.compute.mvau.op import mvau_kernel

    return mvau_kernel().compile()


def test_generated_entries_carry_an_origin(mvau_space):
    """Every generated entry says what made it."""
    assert "fold dial" in mvau_space.origin_of("SIMD")
    assert "stream width" in mvau_space.origin_of("stream_width.inp")
    assert "merged" in mvau_space.origin_of("accDataType")
    assert "projected" in mvau_space.origin_of("sources")


def test_fold_dial_origin_names_the_ports_it_folds(mvau_space):
    """The useful part: not just "generated", but generated FROM WHAT. This is what turns
    "why does SIMD have this domain?" into a lookup instead of a hunt."""
    origin = mvau_space.origin_of("SIMD")
    assert "inp" in origin and "weights" in origin, origin


def test_describe_entry_is_a_one_line_trace(mvau_space):
    desc = mvau_space.describe_entry("stream_width.out")
    assert "stream_width.out" in desc
    assert "derived" in desc
    assert "generated" in desc
    assert "reads" in desc  # its declared deps, so the next hop is visible


def test_authored_entries_have_no_origin(mvau_space):
    """An op-authored entry needs none: its name and file already say where it lives.
    Empty origin is the signal "a human wrote this", which is itself information."""
    assert mvau_space.origin_of("thresholdDataType") == ""


def test_origin_of_unknown_name_raises(mvau_space):
    with pytest.raises(KeyError):
        mvau_space.origin_of("no.such.entry")


def test_generated_rule_reasons_carry_provenance():
    """The payoff: a generated rule's rejection says which mechanism generated it."""
    space = DesignSpace(
        axes=(),
        derived=(Derived("x", lambda p, c: 1),),
        predicates=(
            Predicate(lambda p, c: "nope", "a rule", origin="generated: by the test"),
        ),
    ).finalize()
    r = resolve(space, Context(), {})
    assert isinstance(r, Illegal)
    assert r.reasons == ("nope [generated: by the test]",)


def test_authored_rule_reasons_are_unchanged():
    """A hand-written rule's description already names its intent, so its reason must not
    gain noise. Only generated entries carry an origin."""
    space = DesignSpace(
        axes=(),
        derived=(Derived("x", lambda p, c: 1),),
        predicates=(Predicate(lambda p, c: "nope", "a rule"),),
    ).finalize()
    r = resolve(space, Context(), {})
    assert isinstance(r, Illegal)
    assert r.reasons == ("nope",)


def test_origin_does_not_affect_resolution(mvau_space):
    """Metadata only. Two spaces differing solely in origin must resolve identically —
    the property that stops provenance becoming a second source of truth."""
    plain = Derived("v", lambda p, c: 41)
    tagged = Derived("v", lambda p, c: 41, origin="generated: somewhere")
    a = DesignSpace(axes=(), derived=(plain,)).finalize()
    b = DesignSpace(axes=(), derived=(tagged,)).finalize()
    assert dict(resolve(a, Context(), {})) == dict(resolve(b, Context(), {}))
    assert a.stratum_of(plain) == b.stratum_of(tagged)
