services:
  dev:
    working_dir: /workspace/finn
    volumes:
      - .:/workspace/finn
    environment:
      FINN_ROOT: /workspace/finn
      FINN_BUILD_DIR: /workspace/finn/.finn-build
      FINN_DEPS: frozen
