# Copyright (C) 2026, Advanced Micro Devices, Inc.
# SPDX-License-Identifier: BSD-3-Clause

"""Max pooling over FinnLib's HLS ``pooling_stream``: the first HLS kernel.

``pooling_stream`` (FinnLib ``hls/nonlin/pooling.hpp``) is a reduction alone: it
takes the maximum of the beats it is given until one arrives with ``last``, and
then presents it. It does not walk a feature map: the window is the channel's
(decision K2). The kernel's input port reads an ``(H, W, C)`` tensor through the
window, ``(oh * SH + kh, ow * SW + kw, c)``, on the schedule ``(oh, ow, c, kh, kw)``
with ``c`` folded by PE, and closes each window with the marker of its innermost
two indices (``closes``), so the channel's adapter (``input_gen``) presents the
windows in order and its loop-end marker becomes the stream's TLAST, as dotp's
activation TLAST closes each reduction. Its output reads ``(oh, ow, c)``, presented
after each window (``reduces``), PE channels a beat, in the input's element: the
maximum of values in a range stays in it.

The module is an HLS top that FINN writes from the point's values (``pool_top``,
an ``HlsSource``): ``hls::vector`` lanes of the element's ``ap_int``/``ap_uint``,
glue from the AXIS beat and its TLAST to ``pooling_stream``'s ``flit_t`` and from
its results to the output beat, lane zero lowest, and ``pooling_stream`` with an
elementwise ``std::max``. It runs on ``ap_clk`` and ``ap_rst_n``; its AXIS pins are
spelled as HLS spells them (``s_axis_TDATA``). Its period is the platform's.

Its domain is what that hardware takes: ordinary integers (``max`` over
``ap_int``/``ap_uint``), any window and stride its channel can present, any PE
dividing the channels. Its computation's reference is test-side until a KernelOp
reaches it (decision KT12 A1): ``tests/kernels/specs/pool.py``.
"""

from __future__ import annotations

from finn.core.space import (
    ConstraintGroup,
    Decision,
    Param,
    Rejected,
    constraint,
    derived,
    reject,
)
from finn.dataflow.datatypes import QONNXDataType
from finn.dataflow.schedule import Affine, Index, Schedule
from finn.kernels.artifacts.abi import Endpoint
from finn.kernels.artifacts.contributions import CopiedSource, HlsSource
from finn.kernels.artifacts.hls import axis_type
from finn.kernels.base import Kernel, factor_domain
from finn.kernels.channels import Channel
from finn.kernels.port import AxiStreamPort
from finn.kernels.target import Platform
from finn.kernels.transport import AxisSpelling
from finn.kernels.values.domains import Integer
from finn.kernels.values.semantics import QONNX_DATATYPE_VALUE_SEMANTICS

oh, ow, c, kh, kw = (Index(name) for name in ("oh", "ow", "c", "kh", "kw"))

#: The FinnLib headers ``pool_top`` includes, and the ones they include.
HEADERS = tuple(
    CopiedSource("finnlib", path)
    for path in ("hls/nonlin/pooling.hpp", "hls/util/util.hpp", "hls/shape/input_gen.hpp")
)
#: Every submodule named after its top, so that two configurations share a netlist; no
#: deadlock detector, which is simulation-only logic.
DIRECTIVES = ("config_rtl -module_auto_prefix", "config_rtl -deadlock_detection none")
#: The elements its top takes: ordinary integers, as ``ap_int``/``ap_uint`` lanes.
ELEMENTS = Integer()


def element_type(dtype: QONNXDataType) -> str:
    """The C++ type of an ordinary integer element: ``ap_int<b>`` or ``ap_uint<b>``."""
    return f"{'ap_int' if dtype.signed() else 'ap_uint'}<{dtype.bitwidth()}>"


def pool_top(name: str, element: QONNXDataType, pe: int, input_bits: int, output_bits: int) -> str:
    """The text of the HLS top ``name``: ``pooling_stream`` taking the maximum of each
    window of PE ``element`` lanes, from an AXIS input of ``input_bits`` with TLAST
    closing each window to an AXIS output of ``output_bits``, lanes low first."""
    bits = element.bitwidth()
    return f"""// Generated by finn.kernels.pool -- do not edit.
#include <ap_axi_sdata.h>
#include <ap_int.h>
#include <hls_stream.h>
#include <hls_vector.h>
#include "pooling.hpp"
#include "util.hpp"

using Element = {element_type(element)};
using Lanes = hls::vector<Element, {pe}>;
using InBeat = {axis_type(input_bits, True)};
using OutBeat = {axis_type(output_bits, False)};

// An input beat as pooling_stream's flit: its lanes, low first, and its TLAST.
void from_axis(hls::stream<InBeat> &src, hls::stream<flit_t<Lanes>> &dst) {{
#pragma HLS pipeline II=1 style=flp
	if(!src.empty()) {{
		InBeat const  beat = src.read();
		Lanes  lanes;
		for(unsigned  i = 0; i < {pe}; i++) {{
#pragma HLS unroll
			lanes[i] = Element(ap_uint<{bits}>(beat.data.range({bits}*i + {bits - 1}, {bits}*i)));
		}}
		dst.write(flit_t<Lanes>(beat.last, lanes));
	}}
}}

// A result as an output beat: its lanes, low first, its padding zero.
void to_axis(hls::stream<Lanes> &src, hls::stream<OutBeat> &dst) {{
#pragma HLS pipeline II=1 style=flp
	if(!src.empty()) {{
		Lanes const  lanes = src.read();
		OutBeat  beat = 0;
		for(unsigned  i = 0; i < {pe}; i++) {{
#pragma HLS unroll
			ap_uint<{bits}> const  lane = lanes[i].range({bits - 1}, 0);
			beat.range({bits}*i + {bits - 1}, {bits}*i) = lane;
		}}
		dst.write(beat);
	}}
}}

void {name}(hls::stream<InBeat> &s_axis, hls::stream<OutBeat> &m_axis) {{
#pragma HLS interface axis port=s_axis
#pragma HLS interface axis port=m_axis
#pragma HLS interface ap_ctrl_none port=return
#pragma HLS dataflow disable_start_propagation

	// Internal FIFOs, as FinnLib's own tops decouple their AXI streams.
	static hls::stream<flit_t<Lanes>>  src0;
	static hls::stream<Lanes>  dst0;
#pragma HLS stream variable=src0 depth=2
#pragma HLS stream variable=dst0 depth=2

	from_axis(s_axis, src0);
	pooling_stream(src0, dst0, [](Lanes const &a, Lanes const &b) {{
#pragma HLS inline
		Lanes  y;
		for(unsigned  i = 0; i < {pe}; i++) {{
#pragma HLS unroll
			y[i] = std::max(a[i], b[i]);
		}}
		return  y;
	}});
	to_axis(dst0, m_axis);
}}
"""


class PoolKernel(Kernel):
    """Max pooling of each ``window`` at ``stride`` (rows, columns) of an HWC tensor;
    see the module docstring."""

    id = "finnlib.pooling_stream"
    version = 1
    # The stem of its HLS top: the module is ``finn_pool_<key16>``.
    rtl_module = "finn_pool"

    window: tuple[int, int] = Param()
    stride: tuple[int, int] = Param()
    platform: Platform = Param()
    input_channel: Channel = Param(required=False)
    output_channel: Channel = Param(required=False)

    @constraint
    def geometry_supported(self) -> bool | Rejected:
        for name, pair in (("window", self.window), ("stride", self.stride)):
            if len(pair) != 2 or any(type(value) is not int or value < 1 for value in pair):
                return reject("pool-geometry", f"a {name} is two positive integers, not {pair}")
        return True

    @derived
    def extents(self) -> dict[Index, int] | Rejected:
        """The window's extents are its own, and the windows' from the input: as many as
        fit whole, ``(H - KH) // SH + 1`` a row (no padding: a pad is its own stage). The
        channels are bound from the tensors, as is the output, which must agree."""
        (rows, columns), (row_step, column_step) = self.window, self.stride
        shape = self.input_channel.tensor.shape
        if len(shape) != 3 or shape[0] < rows or shape[1] < columns:
            return reject("pool-geometry", f"a {rows}x{columns} window fits no HWC {shape}")
        windows = {
            oh: (shape[0] - rows) // row_step + 1,
            ow: (shape[1] - columns) // column_step + 1,
        }
        return self._bound({kh: rows, kw: columns, **windows})

    pe: int = Decision(domain=factor_domain(c))

    @derived
    def input_index(self) -> tuple[Affine, ...]:
        rows, columns = self.stride
        return (oh * rows + kh, ow * columns + kw, Affine.of(c))

    @derived
    def schedule(self) -> Schedule | Rejected:
        """Window by window, PE channels a beat, the window's positions innermost."""
        return self.bound_schedule(order=(oh, ow, c, kh, kw), factors={c: self.pe})

    @derived
    def frame_cycles(self) -> int:
        """Its schedule's beats, one a cycle at best: an input beat a cycle."""
        return self.schedule.beat_count

    input = AxiStreamPort(
        name="s_axis",
        endpoint=Endpoint.TARGET,
        channel=input_channel,
        admits=ELEMENTS,
        schedule=schedule,
        index=input_index,
        lanes=(c,),
        closes=(kh, kw),
        spelling=AxisSpelling.UPPER,
    )

    @derived(semantics=QONNX_DATATYPE_VALUE_SEMANTICS)
    def element_dtype(self) -> QONNXDataType:
        """The input's element: a window's maximum is one of its values."""
        return self.input.element.dtype

    @derived
    def element_range(self) -> tuple[int, ...]:
        found = self.input.element.value_range
        return () if found is None else tuple(found)

    output = AxiStreamPort(
        name="m_axis",
        endpoint=Endpoint.INITIATOR,
        channel=output_channel,
        admits=ELEMENTS,
        schedule=schedule,
        index=(oh, ow, c),
        lanes=(c,),
        reduces=(kh, kw),
        dtype=element_dtype,
        value_range=element_range,
        spelling=AxisSpelling.UPPER,
    )

    @constraint
    def element_supported(self) -> bool | Rejected:
        """An ordinary integer: ``std::max`` over ``ap_int`` or ``ap_uint`` lanes."""
        return ELEMENTS.check(self.input_channel.tensor.element.dtype)

    admission = ConstraintGroup(geometry_supported, element_supported)

    def sources(self) -> tuple[HlsSource, ...]:
        element, pe = self.element_dtype, self.pe
        input_bits, output_bits = self.input.axis.carrier_bits, self.output.axis.carrier_bits
        return (
            HlsSource.request(
                type(self).rtl_module,
                lambda name: pool_top(name, element, pe, input_bits, output_bits),
                HEADERS,
                self.platform.period_ns,
                DIRECTIVES,
            ),
        )


__all__ = ["DIRECTIVES", "HEADERS", "PoolKernel", "element_type", "pool_top"]
