# Copyright (C) 2026, Advanced Micro Devices, Inc.
# SPDX-License-Identifier: BSD-3-Clause

"""MVAU wrapper and stitch-shim rendering boundary."""

from __future__ import annotations

from collections.abc import Mapping

from finn.dataflow.artifacts import TargetIdentity

#: The generated top is FINN's own, not either Kernel's.
WRAPPER_MODULE = "finn.dataflow.mvau.decomposed_wrapper"

#: The wrapper's control signals, and which of the two clocks is primary.
PRIMARY_CLOCK = "ap_clk"
DOUBLED_CLOCK = "ap_clk2x"
RESET_SIGNAL = "ap_rst_n"


def _literal(value: object) -> str:
    return str(int(value)) if isinstance(value, bool) else str(value)


def _parameter_list(values: Mapping[str, object]) -> str:
    return ",\n        ".join(f".{name}({_literal(values[name])})" for name in sorted(values))


def byte_aligned(bits: int) -> int:
    """Return the AXI byte-aligned width for a logical stream width."""

    return ((bits + 7) // 8) * 8


def render_clock_constraints(target: TargetIdentity) -> str:
    """Render the primary and derived doubled-clock constraints."""

    period = target.clock_period_ns
    return (
        f"create_clock -period {period} -name {PRIMARY_CLOCK} "
        f"[get_ports {PRIMARY_CLOCK}]\n"
        f"create_clock -period {period / 2} -name {DOUBLED_CLOCK} "
        f"[get_ports {DOUBLED_CLOCK}]\n"
    )


def render_decomposed_wrapper(
    module_name: str,
    replay: Mapping[str, object],
    compute: Mapping[str, object],
    *,
    activation_bits: int,
    weight_bits: int,
    output_bits: int,
) -> str:
    """Render the replay-buffer plus dot-product SystemVerilog top."""

    return f"""// Generated by finn.dataflow.mvau.decomposed_provider -- do not edit.
// The decomposed MVAU: finn replay_buffer -> finnlib dotp_axi.
module {module_name} #(
    parameter WSTREAM = {byte_aligned(weight_bits)},
    parameter ISTREAM = {byte_aligned(activation_bits)},
    parameter OSTREAM = {byte_aligned(output_bits)}
)(
    input  logic ap_clk,
    input  logic ap_clk2x,
    input  logic ap_rst_n,
    input  logic [WSTREAM-1:0] in1_V_tdata,
    input  logic in1_V_tvalid,
    output logic in1_V_tready,
    input  logic [ISTREAM-1:0] in0_V_tdata,
    input  logic in0_V_tvalid,
    output logic in0_V_tready,
    output logic [OSTREAM-1:0] out0_V_tdata,
    output logic out0_V_tvalid,
    input  logic out0_V_tready
);
    localparam int unsigned REPLAY_W = {_literal(replay["W"])};

    uwire rst = !ap_rst_n;
    uwire [REPLAY_W-1:0] replayed_tdata;
    uwire replayed_tvalid;
    uwire replayed_tlast;
    uwire replayed_tready;

    replay_buffer #(
        {_parameter_list(replay)}
    ) activation_replay (
        .clk(ap_clk), .rst(rst),
        .idat(in0_V_tdata[REPLAY_W-1:0]),
        .ivld(in0_V_tvalid),
        .irdy(in0_V_tready),
        .odat(replayed_tdata),
        .olast(replayed_tlast),
        .ofin(),
        .ovld(replayed_tvalid),
        .ordy(replayed_tready)
    );

    dotp_axi #(
        {_parameter_list(compute)}
    ) dot_product (
        .ap_clk(ap_clk), .ap_clk2x(ap_clk2x), .ap_rst_n(ap_rst_n),
        .s_axis_weights_tdata(in1_V_tdata),
        .s_axis_weights_tvalid(in1_V_tvalid),
        .s_axis_weights_tready(in1_V_tready),
        .s_axis_input_tdata(replayed_tdata),
        .s_axis_input_tvalid(replayed_tvalid),
        .s_axis_input_tlast(replayed_tlast),
        .s_axis_input_tready(replayed_tready),
        .m_axis_output_tdata(out0_V_tdata),
        .m_axis_output_tvalid(out0_V_tvalid),
        .m_axis_output_tready(out0_V_tready)
    );
endmodule
"""


_WRAPPER_PORTS: tuple[tuple[str, str, str | None], ...] = (
    ("ap_clk", "input", None),
    ("ap_clk2x", "input", None),
    ("ap_rst_n", "input", None),
    ("in1_V_tdata", "input", "WSTREAM"),
    ("in1_V_tvalid", "input", None),
    ("in1_V_tready", "output", None),
    ("in0_V_tdata", "input", "ISTREAM"),
    ("in0_V_tvalid", "input", None),
    ("in0_V_tready", "output", None),
    ("out0_V_tdata", "output", "OSTREAM"),
    ("out0_V_tvalid", "output", None),
    ("out0_V_tready", "input", None),
)


def render_stitch_shim(
    module_name: str,
    *,
    activation_bits: int,
    weight_bits: int,
    output_bits: int,
) -> str:
    """Render the plain-Verilog wrapper required by Vivado block designs."""

    widths = {"WSTREAM": weight_bits, "ISTREAM": activation_bits, "OSTREAM": output_bits}
    declarations = ",\n    ".join(
        f"{direction} wire {f'[{parameter}-1:0] ' if parameter else ''}{name}"
        for name, direction, parameter in _WRAPPER_PORTS
    )
    connections = ",\n        ".join(f".{name}({name})" for name, _, _ in _WRAPPER_PORTS)
    parameters = ",\n    ".join(
        f"parameter {name} = {byte_aligned(bits)}" for name, bits in widths.items()
    )
    overrides = ", ".join(f".{name}({name})" for name in widths)
    return f"""// Generated by finn.dataflow.mvau.decomposed_provider -- do not edit.
// Plain-Verilog stitching top: create_bd_cell cannot reference a .sv top file.
module {module_name}_wrapper #(
    {parameters}
)(
    {declarations}
);
    {module_name} #({overrides}) core (
        {connections}
    );
endmodule
"""


__all__ = [
    "DOUBLED_CLOCK",
    "PRIMARY_CLOCK",
    "RESET_SIGNAL",
    "WRAPPER_MODULE",
    "byte_aligned",
    "render_clock_constraints",
    "render_decomposed_wrapper",
    "render_stitch_shim",
]
