# Copyright (C) 2026, Advanced Micro Devices, Inc.
# SPDX-License-Identifier: BSD-3-Clause
"""Typed design-space authoring, immutable specialization and public services."""

from .declarations import (
    AcceptedViewRef,
    BoundView,
    ChoiceView,
    Const,
    Constraint,
    ConstraintGroup,
    Decision,
    DecisionRef,
    Dependency,
    Derived,
    Param,
    Readiness,
    Space,
    Subspace,
    SubspaceChoice,
    ValueKey,
    ValueRef,
    View,
    ViewKey,
    constraint,
    derived,
    full_answer,
    optional,
    view,
)
from .compiler import SpaceModel, compile_space
from .domains import Domain, divisors_of, domain, finite
from .edits import Edit, EditOutcome, EditRequest, RefinementReport
from .errors import DefinitionError, EvaluationError
from .results import (
    Answer,
    ConstraintAssessment,
    Decided,
    DecisionState,
    Finding,
    FindingKind,
    Inapplicable,
    MissingInput,
    NotApplicable,
    ReadinessAssessment,
    Rejected,
    Unresolved,
    ViewAssessment,
    reject,
)
from .semantics import ValueSemantics, default_semantics
from . import codecs, conformance, extensions, inspection, selections
from .codecs import CodecBinding, JSONValue, SelectionSchema, ValueCodec, codec_for
from .references import DecisionHandle, ValueHandle
from .selections import Selection, SelectionChange, SelectionEntry
from .extensions import ScopeBuilder
from .expressions import Expr

__all__ = [
    "conformance",
    "AcceptedViewRef",
    "Answer",
    "BoundView",
    "ChoiceView",
    "CodecBinding",
    "Const",
    "Constraint",
    "ConstraintAssessment",
    "ConstraintGroup",
    "Decided",
    "Decision",
    "DecisionRef",
    "DecisionHandle",
    "DecisionState",
    "DefinitionError",
    "Dependency",
    "Derived",
    "Domain",
    "Edit",
    "EditOutcome",
    "EditRequest",
    "EvaluationError",
    "Expr",
    "Finding",
    "FindingKind",
    "Inapplicable",
    "JSONValue",
    "MissingInput",
    "NotApplicable",
    "Param",
    "Readiness",
    "ReadinessAssessment",
    "RefinementReport",
    "Rejected",
    "ScopeBuilder",
    "Selection",
    "SelectionChange",
    "SelectionEntry",
    "SelectionSchema",
    "Space",
    "SpaceModel",
    "Subspace",
    "SubspaceChoice",
    "Unresolved",
    "ValueKey",
    "ValueCodec",
    "ValueHandle",
    "ValueRef",
    "ValueSemantics",
    "View",
    "ViewAssessment",
    "ViewKey",
    "compile_space",
    "codec_for",
    "codecs",
    "constraint",
    "default_semantics",
    "derived",
    "divisors_of",
    "domain",
    "finite",
    "extensions",
    "full_answer",
    "inspection",
    "optional",
    "reject",
    "selections",
    "view",
]
