############################################################################
# Copyright (C) 2025, Advanced Micro Devices, Inc.
# All rights reserved.
# Portions of this content consist of AI generated content.
#
# SPDX-License-Identifier: BSD-3-Clause
############################################################################

"""``ArtifactManifest`` — the single source-of-truth for a component's build sources (F9).

A component's HDL/library source list was written down TWICE: as a bare ``Backend.sources``
tuple (filenames, for pool bookkeeping) AND as a hand-built ``StaticFile`` list inside emit
(the same files as full resolved paths, for the build copy). The two could silently drift —
a file added to one but forgotten in the other yields a bundle that RESOLVES fine but FAILS
at elaboration with a missing-module error. On top of that, the *path resolution* (which
in-tree subdir each file lives under — ``finn-rtllib/mvu/`` vs ``deps/finn-hlslib/`` vs
``finn-rtllib/thresholding/hdl/``) was scattered across inline f-strings and per-file
override dicts.

An ``ArtifactManifest`` is the ONE authoritative list: each :class:`SourceFile` carries its
own resolved path, and the manifest optionally names the top module + references the typed
:class:`~finn.kernels.space.artifacts.RtlModule` schema. Both ``Backend.sources`` and emit's
``StaticFile`` list become READERS of the one manifest — the "three readers of one value"
(build copy · pool bookkeeping · rtlsim/IPI source discovery) instead of three hand-lists.
Converges with :attr:`Backend.schema` (2a): both express one authored value, many readers.

Two authoring paths produce a manifest, mirroring the schema story:
* HAND-DECLARED next to the emit/template (the finn-rtllib + custom-RTL baseline).
* GENERATED by :func:`read_abc` from a finnlib ``.abc`` dependency manifest
  (``import``/``read_sv``/``setup_top``) — an OPTIONAL reader above the primitive, not baked
  into ``Backend``.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .artifacts import RtlModule, StaticFile


@dataclass(frozen=True)
class SourceFile:
    """One build source file + where it resolves from.

    ``filename`` is the bare name (``"thresholding.sv"``); ``root`` is the in-tree directory
    it lives under (``"finn-rtllib/thresholding/hdl"``); ``package`` is the packaged-resource
    root the adapter resolves against (``"finn.data"`` for in-tree HDL). ``resource`` is the
    joined path the old inline f-strings hand-built."""

    filename: str
    root: str
    package: str = "finn.data"

    @property
    def resource(self) -> str:
        return f"{self.root}/{self.filename}" if self.root else self.filename

    def as_static(self) -> StaticFile:
        return StaticFile(self.package, self.resource)


@dataclass(frozen=True)
class ArtifactManifest:
    """The single source-of-truth for a component's build artifacts.

    Fields:
        sources: the ordered build source files, each with its resolved path.
        top: the top module name, when the component names one (``.abc`` ``setup_top``).
        schema: the optional typed template contract (shared with :attr:`Backend.schema`).
    """

    sources: tuple[SourceFile, ...] = ()
    top: str | None = None
    schema: RtlModule | None = None

    @property
    def filenames(self) -> tuple[str, ...]:
        """The bare source filenames — what ``Backend.sources`` reads."""
        return tuple(s.filename for s in self.sources)

    def static_files(self) -> tuple[StaticFile, ...]:
        """The ``StaticFile`` refs emit copies into the build — what the emit reads."""
        return tuple(s.as_static() for s in self.sources)

    def resources(self) -> tuple[str, ...]:
        """The resolved resource paths — what rtlsim/IPI source discovery reads."""
        return tuple(s.resource for s in self.sources)


# --- the .abc reader (finnlib dependency manifest → ArtifactManifest) ----------
#
# An .abc file (finnlib/rtl/*.abc) is a small dependency manifest:
#   import  <dep> <dep> ...   # other components to pull in (transitively, by their own .abc)
#   read_sv <file.sv> ...     # source file(s) THIS component provides
#   read_xdc [flags] <file>   # a constraint file (also a build source)
#   set <var> <value>         # a local variable, referenced later as $<var>
#   setup_top <module>        # the top module name
#   setup_tb  <module>        # a testbench top (ignored for the build manifest)
# The transitive source list is: for each component in dependency-first order, its read_sv /
# read_xdc files. This mirrors a linker's dep-before-dependent ordering.


def _subst(token: str, variables: dict[str, str]) -> str:
    """Substitute ``$var`` references from the component's ``set`` variables (e.g.
    ``$self.sv`` → ``dotp_8sx9_dsp58.sv``). Only whole ``$var`` prefixes are replaced,
    longest-name-first so ``$selfx`` never partially matches ``$self``."""
    for var in sorted(variables, key=len, reverse=True):
        token = token.replace(f"${var}", variables[var])
    return token


def _parse_abc(text: str) -> tuple[list[str], list[str], str | None]:
    """Parse one .abc's body into ``(imports, source_files, top)``. Blank lines and ``#``
    comments are skipped; ``import``/``read_sv`` may repeat and list multiple tokens;
    ``read_xdc`` contributes its (flag-stripped) file; ``set`` defines ``$var`` values used
    in later ``read_*`` lines."""
    imports: list[str] = []
    sources: list[str] = []
    top: str | None = None
    variables: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        head, *rest = line.split()
        rest = [_subst(t, variables) for t in rest]
        if head == "import":
            imports.extend(rest)
        elif head == "read_sv":
            sources.extend(rest)
        elif head == "read_xdc" and rest:
            # Flags (``-unmanaged``) and flag-args (``-ref <name>``) precede the file; the
            # constraint file is the LAST token (``read_xdc -unmanaged -ref $self $self.xdc``).
            sources.append(rest[-1])
        elif head == "set" and len(rest) >= 2:
            variables[rest[0]] = rest[1]
        elif head == "setup_top" and rest:
            top = rest[0]
    return imports, sources, top


def read_abc(
    name: str,
    abc_dir,
    *,
    root: str,
    package: str = "finn.data",
) -> ArtifactManifest:
    """Read the finnlib component ``name`` (its ``<name>.abc`` under ``abc_dir``) into an
    :class:`ArtifactManifest`, resolving ``import`` dependencies transitively.

    ``root``/``package`` locate the resolved source files (the same in-tree resource root the
    hand-declared manifests use). Dependency order is preserved dep-first and de-duplicated,
    so a diamond dep contributes its sources once. The component's own ``setup_top`` becomes
    the manifest ``top``. Raises ``FileNotFoundError`` if a referenced ``.abc`` is missing —
    a real (not silent) source-completeness failure, exactly what F9 is meant to catch."""
    abc_dir = Path(abc_dir)
    ordered: list[str] = []  # sv filenames, dep-first
    seen_files: set[str] = set()
    visiting: set[str] = set()
    resolved: set[str] = set()
    top_holder: dict[str, str | None] = {"top": None}

    def visit(comp: str, is_root: bool) -> None:
        if comp in resolved or comp in visiting:
            return  # already emitted, or a cycle guard (finnlib dep graphs are acyclic)
        visiting.add(comp)
        text = (abc_dir / f"{comp}.abc").read_text()
        imports, sv_files, top = _parse_abc(text)
        for dep in imports:
            visit(dep, is_root=False)
        for f in sv_files:
            if f not in seen_files:
                seen_files.add(f)
                ordered.append(f)
        if is_root:
            top_holder["top"] = top
        visiting.discard(comp)
        resolved.add(comp)

    visit(name, is_root=True)
    sources = tuple(SourceFile(f, root=root, package=package) for f in ordered)
    return ArtifactManifest(sources=sources, top=top_holder["top"])
