# Copyright (C) 2026, Advanced Micro Devices, Inc.
# SPDX-License-Identifier: BSD-3-Clause

"""Composing the two bound Kernels into one buildable artifact.

Each Kernel says what module it is and with which parameters.  Neither says how
they are wired, because wiring two Kernels together is not either Kernel's
business -- it is this assembly's, which is also the only thing that knows the
Network the wiring has to realize.

The generated top is emitted here, from the bindings: every parameter driven
into either core was read out of the design point through that Kernel's own
declared table, never recomputed.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import cast

from finn.dataflow.design import Finding, FindingKind, QualifiedPath
from finn.dataflow.hardware import KernelBinding
from finn.dataflow.mvau.decomposed import (
    ACTIVATION_EDGE,
    DOT_PRODUCT_NODE,
    REPLAY_NODE,
    ActivationReplayKernel,
    DotProductKernel,
)
from finn.dataflow.network import DataflowNetwork
from finn.dataflow.mvau.elaboration import (
    MVAUElaborationError,
    MVAUPhysicalAssociation,
    MVAUPhysicalBoundary,
    MVAUPhysicalComponent,
    MVAUPhysicalConnection,
    MVAUPhysicalControlInterface,
    MVAUPhysicalControlKind,
    MVAUPhysicalDirection,
    MVAUPhysicalElaboration,
    MVAUPhysicalNumericInterface,
    MVAUPhysicalNumericProtocol,
    MVAUSemanticPortRef,
    mvau_elaboration_origin,
)
from finn.dataflow.mvau.compute_kernels import MVAU_COMPUTE_SELECTION, MVAU_REPLAY_SELECTION
from finn.dataflow.mvau.hardware.binding import (
    DecomposedBindings,
    bind_decomposed,
    resolved_manifest,
    source_roots,
    verify_manifest,
)
from finn.dataflow.mvau.source import MVAUResolvedDesign
from finn.dataflow.mvau_problem import MVAUProblemPaths
from finn.dataflow.region import Port

#: The generated top is FINN's own, not either Kernel's.
WRAPPER_MODULE = "finn.dataflow.mvau.decomposed_wrapper"

_COMPOSITION_PATH = QualifiedPath("hardware.mvau.composition")


def _fail(code: str, message: str) -> MVAUElaborationError:
    return MVAUElaborationError(
        (Finding(FindingKind.LIMITATION, code, _COMPOSITION_PATH, message),)
    )


def _literal(value: object) -> str:
    return str(int(value)) if isinstance(value, bool) else str(value)


def _parameter_list(values: Mapping[str, object]) -> str:
    return ",\n        ".join(f".{name}({_literal(values[name])})" for name in sorted(values))


def _byte_aligned(bits: int) -> int:
    return ((bits + 7) // 8) * 8


def render_decomposed_wrapper(
    module_name: str,
    replay: Mapping[str, object],
    compute: Mapping[str, object],
    *,
    activation_bits: int,
    weight_bits: int,
    output_bits: int,
) -> str:
    """The generated top: a replay buffer feeding a dot product.

    Wired exactly as ``mvu_vvu_axi`` wires its internal replay -- the replay's
    ``olast`` becomes the dot product's ``s_axis_input_tlast``, and ``ofin`` is
    left unconnected because the fused core never reads it either.  That
    correspondence is what fixture 5 checks, and it is why this generator and
    that fixture must be the same code.
    """

    return f"""// Generated by finn.dataflow.mvau.decomposed_provider -- do not edit.
// The decomposed MVAU: finn replay_buffer -> finnlib dotp_axi.
module {module_name} #(
    parameter WSTREAM = {_byte_aligned(weight_bits)},
    parameter ISTREAM = {_byte_aligned(activation_bits)},
    parameter OSTREAM = {_byte_aligned(output_bits)}
)(
    input  logic ap_clk,
    input  logic ap_clk2x,
    input  logic ap_rst_n,
    input  logic [WSTREAM-1:0] in1_V_tdata,
    input  logic in1_V_tvalid,
    output logic in1_V_tready,
    input  logic [ISTREAM-1:0] in0_V_tdata,
    input  logic in0_V_tvalid,
    output logic in0_V_tready,
    output logic [OSTREAM-1:0] out0_V_tdata,
    output logic out0_V_tvalid,
    input  logic out0_V_tready
);
    localparam int unsigned REPLAY_W = {_literal(replay["W"])};

    uwire rst = !ap_rst_n;
    uwire [REPLAY_W-1:0] replayed_tdata;
    uwire replayed_tvalid;
    uwire replayed_tlast;
    uwire replayed_tready;

    replay_buffer #(
        {_parameter_list(replay)}
    ) activation_replay (
        .clk(ap_clk), .rst(rst),
        .idat(in0_V_tdata[REPLAY_W-1:0]),
        .ivld(in0_V_tvalid),
        .irdy(in0_V_tready),
        .odat(replayed_tdata),
        .olast(replayed_tlast),
        .ofin(),
        .ovld(replayed_tvalid),
        .ordy(replayed_tready)
    );

    dotp_axi #(
        {_parameter_list(compute)}
    ) dot_product (
        .ap_clk(ap_clk), .ap_clk2x(ap_clk2x), .ap_rst_n(ap_rst_n),
        .s_axis_weights_tdata(in1_V_tdata),
        .s_axis_weights_tvalid(in1_V_tvalid),
        .s_axis_weights_tready(in1_V_tready),
        .s_axis_input_tdata(replayed_tdata),
        .s_axis_input_tvalid(replayed_tvalid),
        .s_axis_input_tlast(replayed_tlast),
        .s_axis_input_tready(replayed_tready),
        .m_axis_output_tdata(out0_V_tdata),
        .m_axis_output_tvalid(out0_V_tvalid),
        .m_axis_output_tready(out0_V_tready)
    );
endmodule
"""


# -- elaboration -------------------------------------------------------------


def _numeric(
    interface_id: str,
    component_id: str,
    direction: MVAUPhysicalDirection,
    port: Port,
    region_id: str,
    data: str,
    valid: str,
    ready: str,
) -> MVAUPhysicalNumericInterface:
    return MVAUPhysicalNumericInterface(
        interface_id,
        component_id,
        direction,
        MVAUPhysicalNumericProtocol.AXI_STREAM,
        port.logical_beat_bits,
        _byte_aligned(port.logical_beat_bits),
        data,
        valid,
        ready,
        (MVAUSemanticPortRef(region_id, port.id),),
    )


@dataclass(frozen=True)
class _Provenance:
    """What one physical object traces back to, and nothing it does not."""

    regions: tuple[str, ...]
    ports: tuple[MVAUSemanticPortRef, ...]
    decisions: tuple[QualifiedPath, ...]
    kernels: tuple[str, ...]


def _provenance(
    binding: KernelBinding,
    semantic_kernel_id: str,
    selection: QualifiedPath,
    network: DataflowNetwork,
) -> _Provenance:
    """Everything behind one bound Kernel: what it covers and what chose it.

    Three kinds of decision, and all three belong.  The selection that picked
    the semantic alternative, the Kernel's own committed choices, and every
    decision it imports -- ``compute_pumping`` configured this core, and
    ``PE``/``SIMD`` size it without being its to pick.  The replay buffer has no
    choices of its own at all, so imports are the only reason its record is not
    empty, and an empty record for hardware the folding literally dimensions
    would be the provenance failure this exists to prevent.
    """

    node_id = binding.regions[0].node_id
    return _Provenance(
        (node_id,),
        tuple(
            MVAUSemanticPortRef(node_id, interface.port.id)
            for interface in network.node(node_id).region.interfaces
        ),
        tuple(
            dict.fromkeys(
                (
                    selection,
                    *sorted(binding.kernel.assignments, key=str),
                    *binding.kernel.declaration.imported_decisions,
                )
            )
        ),
        tuple(sorted({semantic_kernel_id, binding.kernel_id})),
    )


def _merge(items: tuple[_Provenance, ...]) -> _Provenance:
    """The union, for an object that genuinely spans several bindings."""

    def unique(values: tuple[object, ...]) -> tuple[object, ...]:
        return tuple(dict.fromkeys(values))

    return _Provenance(
        cast("tuple[str, ...]", unique(tuple(v for i in items for v in i.regions))),
        cast(
            "tuple[MVAUSemanticPortRef, ...]",
            unique(tuple(v for i in items for v in i.ports)),
        ),
        cast(
            "tuple[QualifiedPath, ...]",
            unique(tuple(v for i in items for v in i.decisions)),
        ),
        cast("tuple[str, ...]", unique(tuple(v for i in items for v in i.kernels))),
    )


def _component(binding: KernelBinding, prefix: str, parent: str) -> MVAUPhysicalComponent:
    """The Kernel's own component, placed under this source scope.

    A Kernel names itself ``dot_product`` and knows nothing about where that
    instance sits or what encloses it.  Both are this assembly's to supply: the
    placement prefix, and the generated wrapper the two cores live inside.
    """

    (declared,) = type(binding.kernel).elaborate(binding)
    return MVAUPhysicalComponent(
        f"{prefix}.{declared.id}", declared.module, parent, declared.parameters
    )


def elaborate_decomposed(resolved: MVAUResolvedDesign) -> MVAUPhysicalElaboration:
    """Elaborate the decomposed slice into a replay core and a dot-product core."""

    bindings = bind_decomposed(resolved)
    return compose(resolved, bindings)


def compose(resolved: MVAUResolvedDesign, bindings: DecomposedBindings) -> MVAUPhysicalElaboration:
    """Wire two bound Kernels into one physical elaboration."""

    network = bindings.network
    replay_region = bindings.replay.regions[0].region
    compute_region = bindings.compute.regions[0].region
    activation_in = replay_region.input_interface("activation_in").port
    activation_out = replay_region.output_interface("activation_out").port
    dot_activation = compute_region.input_interface("activation").port
    weight = compute_region.input_interface("weight").port
    output = compute_region.output_interface("output").port

    source_id = resolved.result.source_association.source_node_id
    prefix = f"{source_id}.compute"
    wrapper_id = f"{prefix}.wrapper"
    replay_component = _component(bindings.replay, prefix, wrapper_id)
    dot_component = _component(bindings.compute, prefix, wrapper_id)
    replay_id = replay_component.id
    dot_id = dot_component.id

    everything = {
        **dict(bindings.replay.parameters),
        **dict(bindings.compute.parameters),
    }
    components = (
        MVAUPhysicalComponent(
            wrapper_id,
            WRAPPER_MODULE,
            parameters=tuple(
                (name, cast("bool | int | float | str", everything[name]))
                for name in sorted(everything)
            ),
        ),
        replay_component,
        dot_component,
    )
    interfaces = (
        _numeric(
            f"{wrapper_id}.activation",
            wrapper_id,
            MVAUPhysicalDirection.INPUT,
            activation_in,
            REPLAY_NODE,
            "in0_V_TDATA",
            "in0_V_TVALID",
            "in0_V_TREADY",
        ),
        _numeric(
            f"{wrapper_id}.weight",
            wrapper_id,
            MVAUPhysicalDirection.INPUT,
            weight,
            DOT_PRODUCT_NODE,
            "in1_V_TDATA",
            "in1_V_TVALID",
            "in1_V_TREADY",
        ),
        _numeric(
            f"{wrapper_id}.output",
            wrapper_id,
            MVAUPhysicalDirection.OUTPUT,
            output,
            DOT_PRODUCT_NODE,
            "out0_V_TDATA",
            "out0_V_TVALID",
            "out0_V_TREADY",
        ),
        _numeric(
            f"{replay_id}.activation_in",
            replay_id,
            MVAUPhysicalDirection.INPUT,
            activation_in,
            REPLAY_NODE,
            "idat",
            "ivld",
            "irdy",
        ),
        _numeric(
            f"{replay_id}.activation_out",
            replay_id,
            MVAUPhysicalDirection.OUTPUT,
            activation_out,
            REPLAY_NODE,
            "odat",
            "ovld",
            "ordy",
        ),
        _numeric(
            f"{dot_id}.activation",
            dot_id,
            MVAUPhysicalDirection.INPUT,
            dot_activation,
            DOT_PRODUCT_NODE,
            "s_axis_input_tdata",
            "s_axis_input_tvalid",
            "s_axis_input_tready",
        ),
        _numeric(
            f"{dot_id}.weight",
            dot_id,
            MVAUPhysicalDirection.INPUT,
            weight,
            DOT_PRODUCT_NODE,
            "s_axis_weights_tdata",
            "s_axis_weights_tvalid",
            "s_axis_weights_tready",
        ),
        _numeric(
            f"{dot_id}.output",
            dot_id,
            MVAUPhysicalDirection.OUTPUT,
            output,
            DOT_PRODUCT_NODE,
            "m_axis_output_tdata",
            "m_axis_output_tvalid",
            "m_axis_output_tready",
        ),
    )
    # Signal names are each core's own, not one convention imposed on all three.
    # ``replay_buffer`` predates the AXI naming and takes ``clk`` with an
    # active-high ``rst``; the generated wrapper is what inverts the reset and
    # bridges the two, so the model has to say which is which.
    controls = (
        MVAUPhysicalControlInterface(
            f"{wrapper_id}.clock", wrapper_id, MVAUPhysicalControlKind.CLOCK, "ap_clk"
        ),
        MVAUPhysicalControlInterface(
            f"{wrapper_id}.clock2x", wrapper_id, MVAUPhysicalControlKind.CLOCK, "ap_clk2x"
        ),
        MVAUPhysicalControlInterface(
            f"{wrapper_id}.reset", wrapper_id, MVAUPhysicalControlKind.RESET, "ap_rst_n"
        ),
        MVAUPhysicalControlInterface(
            f"{replay_id}.clock", replay_id, MVAUPhysicalControlKind.CLOCK, "clk"
        ),
        MVAUPhysicalControlInterface(
            f"{replay_id}.reset", replay_id, MVAUPhysicalControlKind.RESET, "rst"
        ),
        MVAUPhysicalControlInterface(
            f"{dot_id}.clock", dot_id, MVAUPhysicalControlKind.CLOCK, "ap_clk"
        ),
        # Only the dot product runs a doubled clock; the replay never does.
        MVAUPhysicalControlInterface(
            f"{dot_id}.clock2x", dot_id, MVAUPhysicalControlKind.CLOCK, "ap_clk2x"
        ),
        MVAUPhysicalControlInterface(
            f"{dot_id}.reset", dot_id, MVAUPhysicalControlKind.RESET, "ap_rst_n"
        ),
    )
    connections = (
        MVAUPhysicalConnection(
            "compute.wrapper_activation",
            (f"{wrapper_id}.activation", f"{replay_id}.activation_in"),
        ),
        # The one internal edge the Network declares, realized.  Neither Kernel
        # absorbs it, so it is a connection rather than internal wiring.
        MVAUPhysicalConnection(
            "compute.replay_to_dot_product",
            (f"{replay_id}.activation_out", f"{dot_id}.activation"),
            (ACTIVATION_EDGE,),
        ),
        MVAUPhysicalConnection(
            "compute.wrapper_weight", (f"{wrapper_id}.weight", f"{dot_id}.weight")
        ),
        MVAUPhysicalConnection(
            "compute.wrapper_output", (f"{dot_id}.output", f"{wrapper_id}.output")
        ),
    )
    interfaces_by_id = {item.id: item for item in interfaces}
    boundary_interface = {
        (REPLAY_NODE, "activation_in"): f"{wrapper_id}.activation",
        (DOT_PRODUCT_NODE, "weight"): f"{wrapper_id}.weight",
        (DOT_PRODUCT_NODE, "output"): f"{wrapper_id}.output",
    }
    boundaries = tuple(
        MVAUPhysicalBoundary(
            boundary.id,
            boundary_interface[(boundary.endpoint.node_id, boundary.endpoint.port_id)],
            MVAUSemanticPortRef(boundary.endpoint.node_id, boundary.endpoint.port_id),
        )
        for boundary in network.boundaries
    )

    owners = (
        resolved.result.source_association.source_node_id,
        *resolved.result.source_association.fused_source_node_ids,
    )
    # Provenance is per binding, not one payload shared by everything.  A single
    # merged record makes the replay component claim the dot product's Kernel
    # and the dot product claim the replay's, which is worse than saying
    # nothing: it is a specific false statement about what realizes what.
    by_component = {
        replay_id: _provenance(
            bindings.replay,
            ActivationReplayKernel.id,
            MVAU_REPLAY_SELECTION.paths.kernel,
            network,
        ),
        dot_id: _provenance(
            bindings.compute,
            DotProductKernel.id,
            MVAU_COMPUTE_SELECTION.paths.kernel,
            network,
        ),
    }
    # The wrapper and every connection through it span both, so their record is
    # the union -- which is what a union is for, rather than the default.
    everything_covered = _merge(tuple(by_component.values()))
    by_component[wrapper_id] = everything_covered

    def association(
        physical_id: str,
        provenance: _Provenance,
        ports: tuple[MVAUSemanticPortRef, ...] | None = None,
        edges: tuple[str, ...] = (),
    ) -> MVAUPhysicalAssociation:
        return MVAUPhysicalAssociation(
            physical_id,
            owners,
            provenance.regions,
            provenance.ports if ports is None else ports,
            edges,
            provenance.decisions,
            provenance.kernels,
            (),
        )

    associations = (
        *(association(item.id, by_component[item.id]) for item in components),
        # An interface belongs to exactly one component, and its semantic ports
        # are already declared on it -- so it inherits that component's record
        # and narrows the ports to the ones it actually carries.
        *(
            association(item.id, by_component[item.component_id], item.semantic_ports)
            for item in interfaces
        ),
        # A connection spans the components it joins.
        *(
            association(
                item.id,
                _merge(
                    tuple(
                        by_component[interfaces_by_id[interface].component_id]
                        for interface in item.interface_ids
                    )
                ),
                edges=item.semantic_edge_ids,
            )
            for item in connections
        ),
    )
    return MVAUPhysicalElaboration(
        source_id,
        mvau_elaboration_origin(resolved),
        resolved.result,
        cast(str, resolved.point.problem[MVAUProblemPaths.TARGET_FPGA_PART]),
        cast(float, resolved.point.problem[MVAUProblemPaths.TARGET_CLOCK_PERIOD_NS]),
        components,
        interfaces,
        controls,
        connections,
        boundaries,
        associations,
    )


# -- artifact requirements ---------------------------------------------------


@dataclass(frozen=True)
class MVAUDecomposedArtifactRequirements:
    """Everything needed to produce the decomposed RTL, and nothing ambient.

    Deliberately not ``MVAURTLArtifactRequirements``: that value exists to drive
    the legacy ``MVAU_rtl`` custom op, which emits the fused core and cannot emit
    this one.  The decomposed path generates its own top, so it carries the
    generated text rather than the inputs to someone else's generator.
    """

    top_module_name: str
    target_fpga_part: str
    clock_period_ns: float
    parameters: tuple[tuple[str, bool | int | float | str], ...]
    #: ``(id, absolute path)`` in compile order.
    source_dependencies: tuple[tuple[str, str], ...]
    wrapper_file_name: str
    wrapper_source: str
    elaboration: MVAUPhysicalElaboration

    @property
    def finnlib_sources(self) -> tuple[str, ...]:
        return tuple(path for name, path in self.source_dependencies if ".finnlib." in name)


def build_decomposed_artifact_requirements(
    resolved: MVAUResolvedDesign,
    elaboration: MVAUPhysicalElaboration,
    finn_root: str | Path,
    finnlib: str | Path | None = None,
) -> MVAUDecomposedArtifactRequirements:
    """Turn a decomposed elaboration into a self-contained build input."""

    if elaboration.origin != mvau_elaboration_origin(resolved):
        raise _fail(
            "mvau-decomposed-origin-mismatch",
            "the elaboration was not produced from this exact selected point",
        )
    if elaboration.semantic_result != resolved.result:
        raise _fail(
            "mvau-decomposed-result-mismatch",
            "the elaboration does not belong to the selected semantic result",
        )
    bindings = bind_decomposed(resolved)
    top = f"{resolved.result.source_association.source_node_id}_decomposed"
    wrapper = elaboration.component(
        f"{resolved.result.source_association.source_node_id}.compute.wrapper"
    )
    replay_region = bindings.replay.regions[0].region
    compute_region = bindings.compute.regions[0].region
    text = render_decomposed_wrapper(
        top,
        dict(bindings.replay.parameters),
        dict(bindings.compute.parameters),
        activation_bits=replay_region.input_interface("activation_in").port.logical_beat_bits,
        weight_bits=compute_region.input_interface("weight").port.logical_beat_bits,
        output_bits=compute_region.output_interface("output").port.logical_beat_bits,
    )
    return MVAUDecomposedArtifactRequirements(
        top,
        elaboration.target_fpga_part,
        elaboration.target_clock_period_ns,
        wrapper.parameters,
        resolved_manifest(bindings, source_roots(finn_root, finnlib)),
        f"{top}.sv",
        text,
        elaboration,
    )


def write_decomposed_artifact(
    requirements: MVAUDecomposedArtifactRequirements, output_directory: str | Path
) -> tuple[str, ...]:
    """Stage the declared sources and the generated top, in compile order.

    Returns the file list a simulator or synthesizer should read, with the
    generated wrapper last because it instantiates everything before it.
    """

    verify_manifest(requirements.source_dependencies)
    output = Path(output_directory).resolve()
    output.mkdir(parents=True, exist_ok=True)
    staged: list[str] = []
    for name, path in requirements.source_dependencies:
        destination = output / f"{name}_{Path(path).name}"
        destination.write_bytes(Path(path).read_bytes())
        staged.append(str(destination))
    wrapper = output / requirements.wrapper_file_name
    wrapper.write_text(requirements.wrapper_source)
    staged.append(str(wrapper))
    return tuple(staged)


__all__ = [
    "WRAPPER_MODULE",
    "MVAUDecomposedArtifactRequirements",
    "build_decomposed_artifact_requirements",
    "compose",
    "elaborate_decomposed",
    "render_decomposed_wrapper",
    "write_decomposed_artifact",
]
