# Copyright (C) 2026, Advanced Micro Devices, Inc.
# SPDX-License-Identifier: BSD-3-Clause

"""Composing the two bound Kernels into one buildable artifact.

Each Kernel says what module it is and with which parameters.  Neither says how
they are wired, because wiring two Kernels together is not either Kernel's
business -- it is this assembly's, which is also the only thing that knows the
Network the wiring has to realize.

The generated top is emitted here, from the bindings: every parameter driven
into either core was read out of the design point through that Kernel's own
declared table, never recomputed.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
import shutil
from typing import cast

from finn.dataflow.authoring.design import DesignRealization
from finn.dataflow.design import Finding, FindingKind, QualifiedPath
from finn.dataflow.hardware import (
    DEFAULT_BUILDER,
    DEFAULT_VLNV,
    NO_ARTIFACT_STORE,
    ArtifactStore,
    BuilderIdentity,
    ComposedArtifactIdentity,
    IpPackageArtifactIdentity,
    HardwareKernel,
    KernelArtifactIdentity,
    PackagedArtifactIdentity,
    SynthesisArtifactIdentity,
    TargetIdentity,
    VlnvIdentity,
    checked_lookup,
    composed_artifact_identity,
    kernel_artifact_identity,
)
from finn.dataflow.hardware.identity import content_hash
from finn.dataflow.mvau.decomposed import (
    ACTIVATION_EDGE,
    DOT_PRODUCT_NODE,
    REPLAY_NODE,
    ActivationReplayKernel,
    DotProductKernel,
)
from finn.dataflow.network import DataflowNetwork
from finn.dataflow.mvau.elaboration import (
    MVAUElaborationError,
    MVAUElaborationOrigin,
    MVAUPhysicalAssociation,
    MVAUPhysicalBoundary,
    MVAUPhysicalComponent,
    MVAUPhysicalConnection,
    MVAUPhysicalControlInterface,
    MVAUPhysicalControlKind,
    MVAUPhysicalDirection,
    MVAUPhysicalElaboration,
    MVAUPhysicalNumericInterface,
    MVAUPhysicalNumericProtocol,
    MVAUSemanticPortRef,
    mvau_elaboration_origin,
)
from finn.dataflow.mvau.compute_kernels import MVAU_COMPUTE_SELECTION, MVAU_REPLAY_SELECTION
from finn.dataflow.mvau.hardware.binding import (
    bind_decomposed,
    resolved_manifest,
    source_roots,
    verify_manifest,
)
from finn.dataflow.mvau.input_supply import (
    DELIVERY_EDGE,
    DELIVERY_NODE,
    FINN_RTL_MEMSTREAM_SUPPLY,
)
from finn.dataflow.mvau.source import MVAUResolvedDesign
from finn.dataflow.mvau_problem import MVAUProblemPaths
from finn.dataflow.region import Port

#: The generated top is FINN's own, not either Kernel's.
WRAPPER_MODULE = "finn.dataflow.mvau.decomposed_wrapper"

#: The wrapper's control signals, and which of the two clocks is primary.
#:
#: One authority, because two stages need it and they must not disagree.  The
#: constraints generator names both clocks and states that the doubled one is
#: *derived* -- half the period, never chosen separately -- and IP packaging
#: has to say which clock the streams are synchronous to.  Answering that
#: separately in each place would be two statements of one fact, and the one
#: that reached the tool would win.
PRIMARY_CLOCK = "ap_clk"
DOUBLED_CLOCK = "ap_clk2x"
RESET_SIGNAL = "ap_rst_n"

_COMPOSITION_PATH = QualifiedPath("hardware.mvau.composition")


def _fail(code: str, message: str) -> MVAUElaborationError:
    return MVAUElaborationError(
        (Finding(FindingKind.LIMITATION, code, _COMPOSITION_PATH, message),)
    )


def _literal(value: object) -> str:
    return str(int(value)) if isinstance(value, bool) else str(value)


def _parameter_list(values: Mapping[str, object]) -> str:
    return ",\n        ".join(f".{name}({_literal(values[name])})" for name in sorted(values))


def _byte_aligned(bits: int) -> int:
    return ((bits + 7) // 8) * 8


def render_decomposed_wrapper(
    module_name: str,
    replay: Mapping[str, object],
    compute: Mapping[str, object],
    *,
    activation_bits: int,
    weight_bits: int,
    output_bits: int,
) -> str:
    """The generated top: a replay buffer feeding a dot product.

    Wired exactly as ``mvu_vvu_axi`` wires its internal replay -- the replay's
    ``olast`` becomes the dot product's ``s_axis_input_tlast``, and ``ofin`` is
    left unconnected because the fused core never reads it either.  That
    correspondence is what fixture 5 checks, and it is why this generator and
    that fixture must be the same code.
    """

    return f"""// Generated by finn.dataflow.mvau.decomposed_provider -- do not edit.
// The decomposed MVAU: finn replay_buffer -> finnlib dotp_axi.
module {module_name} #(
    parameter WSTREAM = {_byte_aligned(weight_bits)},
    parameter ISTREAM = {_byte_aligned(activation_bits)},
    parameter OSTREAM = {_byte_aligned(output_bits)}
)(
    input  logic ap_clk,
    input  logic ap_clk2x,
    input  logic ap_rst_n,
    input  logic [WSTREAM-1:0] in1_V_tdata,
    input  logic in1_V_tvalid,
    output logic in1_V_tready,
    input  logic [ISTREAM-1:0] in0_V_tdata,
    input  logic in0_V_tvalid,
    output logic in0_V_tready,
    output logic [OSTREAM-1:0] out0_V_tdata,
    output logic out0_V_tvalid,
    input  logic out0_V_tready
);
    localparam int unsigned REPLAY_W = {_literal(replay["W"])};

    uwire rst = !ap_rst_n;
    uwire [REPLAY_W-1:0] replayed_tdata;
    uwire replayed_tvalid;
    uwire replayed_tlast;
    uwire replayed_tready;

    replay_buffer #(
        {_parameter_list(replay)}
    ) activation_replay (
        .clk(ap_clk), .rst(rst),
        .idat(in0_V_tdata[REPLAY_W-1:0]),
        .ivld(in0_V_tvalid),
        .irdy(in0_V_tready),
        .odat(replayed_tdata),
        .olast(replayed_tlast),
        .ofin(),
        .ovld(replayed_tvalid),
        .ordy(replayed_tready)
    );

    dotp_axi #(
        {_parameter_list(compute)}
    ) dot_product (
        .ap_clk(ap_clk), .ap_clk2x(ap_clk2x), .ap_rst_n(ap_rst_n),
        .s_axis_weights_tdata(in1_V_tdata),
        .s_axis_weights_tvalid(in1_V_tvalid),
        .s_axis_weights_tready(in1_V_tready),
        .s_axis_input_tdata(replayed_tdata),
        .s_axis_input_tvalid(replayed_tvalid),
        .s_axis_input_tlast(replayed_tlast),
        .s_axis_input_tready(replayed_tready),
        .m_axis_output_tdata(out0_V_tdata),
        .m_axis_output_tvalid(out0_V_tvalid),
        .m_axis_output_tready(out0_V_tready)
    );
endmodule
"""


#: The ports the generated top and its stitching shim both carry, in order.
#:
#: One list, used to declare the shim and to wire the core, so the two cannot
#: drift apart.  ``(name, direction, width parameter or None)``.
_WRAPPER_PORTS: tuple[tuple[str, str, str | None], ...] = (
    ("ap_clk", "input", None),
    ("ap_clk2x", "input", None),
    ("ap_rst_n", "input", None),
    ("in1_V_tdata", "input", "WSTREAM"),
    ("in1_V_tvalid", "input", None),
    ("in1_V_tready", "output", None),
    ("in0_V_tdata", "input", "ISTREAM"),
    ("in0_V_tvalid", "input", None),
    ("in0_V_tready", "output", None),
    ("out0_V_tdata", "output", "OSTREAM"),
    ("out0_V_tvalid", "output", None),
    ("out0_V_tready", "input", None),
)


def render_stitch_shim(
    module_name: str,
    *,
    activation_bits: int,
    weight_bits: int,
    output_bits: int,
) -> str:
    """A plain-Verilog top that instantiates the generated SystemVerilog one.

    Not decoration, and not a style preference.  ``create_bd_cell -type module
    -reference`` **refuses a SystemVerilog top file** -- Vivado answers
    ``[filemgmt 56-195] ... This type is not allowed as the top file in the
    reference`` -- so the generated ``.sv`` top cannot be placed in a block
    design at all.  ``-type hier -reference`` is not the alternative it looks
    like: Vivado reports ``[BD 41-1695] Specified '-reference' ... will be
    ignored while creating 'hier' cell``, so it silently makes an empty
    hierarchy.

    A ``.v`` shim over the same ports is what works, and it is exactly what
    baseline FINN does -- ``matrixvectoractivation_rtl`` stages
    ``{gen_top_module}_wrapper.v`` for the same reason.  With it, Vivado also
    infers ``in0_V``, ``in1_V`` and ``out0_V`` as AXI-Stream bus interfaces
    from the signal naming, so the unit stitches as streams rather than as
    loose pins.

    Verilog-2001 only: no ``logic``, no ``uwire``, no ``.*``.  The generated
    top keeps every SystemVerilog construct it needs, and this reaches it
    through explicit connections, so the RTL fixture 5 validates is untouched.
    """

    widths = {"WSTREAM": weight_bits, "ISTREAM": activation_bits, "OSTREAM": output_bits}
    declarations = ",\n    ".join(
        f"{direction} wire {f'[{parameter}-1:0] ' if parameter else ''}{name}"
        for name, direction, parameter in _WRAPPER_PORTS
    )
    connections = ",\n        ".join(f".{name}({name})" for name, _, _ in _WRAPPER_PORTS)
    parameters = ",\n    ".join(
        f"parameter {name} = {_byte_aligned(bits)}" for name, bits in widths.items()
    )
    overrides = ", ".join(f".{name}({name})" for name in widths)
    return f"""// Generated by finn.dataflow.mvau.decomposed_provider -- do not edit.
// Plain-Verilog stitching top: create_bd_cell cannot reference a .sv top file.
module {module_name}_wrapper #(
    {parameters}
)(
    {declarations}
);
    {module_name} #({overrides}) core (
        {connections}
    );
endmodule
"""


# -- elaboration -------------------------------------------------------------


def _numeric(
    interface_id: str,
    component_id: str,
    direction: MVAUPhysicalDirection,
    port: Port,
    region_id: str,
    data: str,
    valid: str,
    ready: str,
) -> MVAUPhysicalNumericInterface:
    return MVAUPhysicalNumericInterface(
        interface_id,
        component_id,
        direction,
        MVAUPhysicalNumericProtocol.AXI_STREAM,
        port.logical_beat_bits,
        _byte_aligned(port.logical_beat_bits),
        data,
        valid,
        ready,
        (MVAUSemanticPortRef(region_id, port.id),),
    )


@dataclass(frozen=True)
class _Provenance:
    """What one physical object traces back to, and nothing it does not."""

    regions: tuple[str, ...]
    ports: tuple[MVAUSemanticPortRef, ...]
    decisions: tuple[QualifiedPath, ...]
    kernels: tuple[str, ...]


def _provenance(
    kernel: HardwareKernel,
    semantic_kernel_id: str | None,
    selection: QualifiedPath | None,
    network: DataflowNetwork,
) -> _Provenance:
    """Everything behind one bound Kernel: what it covers and what chose it.

    Three kinds of decision, and all three belong.  The selection that picked
    the semantic alternative, the Kernel's own committed choices, and every
    decision it imports -- ``compute_pumping`` configured this core, and
    ``PE``/``SIMD`` size it without being its to pick.  The replay buffer has no
    choices of its own at all, so imports are the only reason its record is not
    empty, and an empty record for hardware the folding literally dimensions
    would be the provenance failure this exists to prevent.
    """

    node_id = next(iter(kernel.regions.values())).node_id
    return _Provenance(
        (node_id,),
        tuple(
            MVAUSemanticPortRef(node_id, interface.port.id)
            for interface in network.node(node_id).region.interfaces
        ),
        tuple(
            dict.fromkeys(
                (
                    *((selection,) if selection is not None else ()),
                    *sorted(kernel.assignments, key=str),
                    *kernel.declaration.imported_decisions,
                )
            )
        ),
        tuple(
            sorted(
                {
                    kernel.kernel_id,
                    *((semantic_kernel_id,) if semantic_kernel_id is not None else ()),
                }
            )
        ),
    )


def _merge(items: tuple[_Provenance, ...]) -> _Provenance:
    """The union, for an object that genuinely spans several bindings."""

    def unique(values: tuple[object, ...]) -> tuple[object, ...]:
        return tuple(dict.fromkeys(values))

    return _Provenance(
        cast("tuple[str, ...]", unique(tuple(v for i in items for v in i.regions))),
        cast(
            "tuple[MVAUSemanticPortRef, ...]",
            unique(tuple(v for i in items for v in i.ports)),
        ),
        cast(
            "tuple[QualifiedPath, ...]",
            unique(tuple(v for i in items for v in i.decisions)),
        ),
        cast("tuple[str, ...]", unique(tuple(v for i in items for v in i.kernels))),
    )


def _component(kernel: HardwareKernel, prefix: str, parent: str) -> MVAUPhysicalComponent:
    """The Kernel's own component, placed under this source scope.

    A Kernel names itself ``dot_product`` and knows nothing about where that
    instance sits or what encloses it.  Both are this assembly's to supply: the
    placement prefix, and the generated wrapper the two cores live inside.
    """

    # ``components()`` and not ``elaborate()``: the former audits what came
    # back against what the Kernel declared, and calling the raw classmethod
    # would take the one assembly that matters straight past the check.
    (declared,) = kernel.components()
    return MVAUPhysicalComponent(
        f"{prefix}.{declared.id}", declared.module, parent, declared.parameters
    )


def elaborate_decomposed(resolved: MVAUResolvedDesign) -> MVAUPhysicalElaboration:
    """Elaborate the decomposed slice into a replay core and a dot-product core."""

    bindings = bind_decomposed(resolved)
    return compose(resolved, bindings)


def compose(
    resolved: MVAUResolvedDesign,
    realization: DesignRealization,
    *,
    origin: MVAUElaborationOrigin | None = None,
) -> MVAUPhysicalElaboration:
    """Wire two bound Kernels into one physical elaboration."""

    network = realization.network
    replay = realization.kernel("replay")
    compute = realization.kernel("compute")
    delivery = realization.kernels.get("delivery")
    expected_edges = (
        (ACTIVATION_EDGE,) if delivery is None else tuple(sorted((ACTIVATION_EDGE, DELIVERY_EDGE)))
    )
    if realization.unabsorbed_edges != expected_edges:
        raise _fail(
            "mvau-dot-product-connection-obligation-mismatch",
            "DotProduct must leave exactly its activation-replay edge for composition",
        )
    replay_region = replay.regions["replay"].region
    compute_region = compute.regions["compute"].region
    activation_in = replay_region.input_interface("activation_in").port
    activation_out = replay_region.output_interface("activation_out").port
    dot_activation = compute_region.input_interface("activation").port
    weight = compute_region.input_interface("weight").port
    output = compute_region.output_interface("output").port

    source_id = resolved.result.source_association.source_node_id
    prefix = f"{source_id}.compute"
    wrapper_id = f"{prefix}.wrapper"
    replay_component = _component(replay, prefix, wrapper_id)
    dot_component = _component(compute, prefix, wrapper_id)
    replay_id = replay_component.id
    dot_id = dot_component.id

    everything = {
        **dict(replay.parameters),
        **dict(compute.parameters),
    }
    components: tuple[MVAUPhysicalComponent, ...] = (
        MVAUPhysicalComponent(
            wrapper_id,
            WRAPPER_MODULE,
            parameters=tuple(
                (name, cast("bool | int | float | str", everything[name]))
                for name in sorted(everything)
            ),
        ),
        replay_component,
        dot_component,
    )
    interfaces: tuple[MVAUPhysicalNumericInterface, ...] = (
        _numeric(
            f"{wrapper_id}.activation",
            wrapper_id,
            MVAUPhysicalDirection.INPUT,
            activation_in,
            REPLAY_NODE,
            # Exactly as the generated wrapper declares them.  These used to be
            # spelled ``in0_V_TDATA``, borrowed from the uppercase convention of
            # HLS-generated wrappers -- but this top is generated here, in
            # lowercase, and SystemVerilog identifiers are case-sensitive.  A
            # consumer taking the reported name into a ``connect_bd_net`` named
            # a pin that did not exist.  Nothing read these until the packaged
            # unit began reporting its ports.
            "in0_V_tdata",
            "in0_V_tvalid",
            "in0_V_tready",
        ),
        _numeric(
            f"{wrapper_id}.weight",
            wrapper_id,
            MVAUPhysicalDirection.INPUT,
            weight,
            DOT_PRODUCT_NODE,
            "in1_V_tdata",
            "in1_V_tvalid",
            "in1_V_tready",
        ),
        _numeric(
            f"{wrapper_id}.output",
            wrapper_id,
            MVAUPhysicalDirection.OUTPUT,
            output,
            DOT_PRODUCT_NODE,
            "out0_V_tdata",
            "out0_V_tvalid",
            "out0_V_tready",
        ),
        _numeric(
            f"{replay_id}.activation_in",
            replay_id,
            MVAUPhysicalDirection.INPUT,
            activation_in,
            REPLAY_NODE,
            "idat",
            "ivld",
            "irdy",
        ),
        _numeric(
            f"{replay_id}.activation_out",
            replay_id,
            MVAUPhysicalDirection.OUTPUT,
            activation_out,
            REPLAY_NODE,
            "odat",
            "ovld",
            "ordy",
        ),
        _numeric(
            f"{dot_id}.activation",
            dot_id,
            MVAUPhysicalDirection.INPUT,
            dot_activation,
            DOT_PRODUCT_NODE,
            "s_axis_input_tdata",
            "s_axis_input_tvalid",
            "s_axis_input_tready",
        ),
        _numeric(
            f"{dot_id}.weight",
            dot_id,
            MVAUPhysicalDirection.INPUT,
            weight,
            DOT_PRODUCT_NODE,
            "s_axis_weights_tdata",
            "s_axis_weights_tvalid",
            "s_axis_weights_tready",
        ),
        _numeric(
            f"{dot_id}.output",
            dot_id,
            MVAUPhysicalDirection.OUTPUT,
            output,
            DOT_PRODUCT_NODE,
            "m_axis_output_tdata",
            "m_axis_output_tvalid",
            "m_axis_output_tready",
        ),
    )
    # Signal names are each core's own, not one convention imposed on all three.
    # ``replay_buffer`` predates the AXI naming and takes ``clk`` with an
    # active-high ``rst``; the generated wrapper is what inverts the reset and
    # bridges the two, so the model has to say which is which.
    controls: tuple[MVAUPhysicalControlInterface, ...] = (
        MVAUPhysicalControlInterface(
            f"{wrapper_id}.clock", wrapper_id, MVAUPhysicalControlKind.CLOCK, "ap_clk"
        ),
        MVAUPhysicalControlInterface(
            f"{wrapper_id}.clock2x", wrapper_id, MVAUPhysicalControlKind.CLOCK, "ap_clk2x"
        ),
        MVAUPhysicalControlInterface(
            f"{wrapper_id}.reset", wrapper_id, MVAUPhysicalControlKind.RESET, "ap_rst_n"
        ),
        MVAUPhysicalControlInterface(
            f"{replay_id}.clock", replay_id, MVAUPhysicalControlKind.CLOCK, "clk"
        ),
        MVAUPhysicalControlInterface(
            f"{replay_id}.reset", replay_id, MVAUPhysicalControlKind.RESET, "rst"
        ),
        MVAUPhysicalControlInterface(
            f"{dot_id}.clock", dot_id, MVAUPhysicalControlKind.CLOCK, "ap_clk"
        ),
        # Only the dot product runs a doubled clock; the replay never does.
        MVAUPhysicalControlInterface(
            f"{dot_id}.clock2x", dot_id, MVAUPhysicalControlKind.CLOCK, "ap_clk2x"
        ),
        MVAUPhysicalControlInterface(
            f"{dot_id}.reset", dot_id, MVAUPhysicalControlKind.RESET, "ap_rst_n"
        ),
    )
    connections: tuple[MVAUPhysicalConnection, ...] = (
        MVAUPhysicalConnection(
            "compute.wrapper_activation",
            (f"{wrapper_id}.activation", f"{replay_id}.activation_in"),
        ),
        # The one internal edge the Network declares, realized.  Neither Kernel
        # absorbs it, so it is a connection rather than internal wiring.
        MVAUPhysicalConnection(
            "compute.replay_to_dot_product",
            (f"{replay_id}.activation_out", f"{dot_id}.activation"),
            (ACTIVATION_EDGE,),
        ),
        MVAUPhysicalConnection(
            "compute.wrapper_weight", (f"{wrapper_id}.weight", f"{dot_id}.weight")
        ),
        MVAUPhysicalConnection(
            "compute.wrapper_output", (f"{dot_id}.output", f"{wrapper_id}.output")
        ),
    )
    if delivery is not None:
        delivery_region = next(iter(delivery.regions.values())).region
        delivery_port = delivery_region.output_interface("weight").port
        delivery_id = f"{source_id}.delivery.wrapper"
        (declared_delivery,) = delivery.components()
        delivery_component = MVAUPhysicalComponent(
            delivery_id,
            declared_delivery.module,
            parameters=declared_delivery.parameters,
        )
        delivery_interface = _numeric(
            f"{delivery_id}.weight",
            delivery_id,
            MVAUPhysicalDirection.OUTPUT,
            delivery_port,
            DELIVERY_NODE,
            "m_axis_0_tdata",
            "m_axis_0_tvalid",
            "m_axis_0_tready",
        )
        delivery_controls = (
            MVAUPhysicalControlInterface(
                f"{delivery_id}.clock",
                delivery_id,
                MVAUPhysicalControlKind.CLOCK,
                "ap_clk",
            ),
            MVAUPhysicalControlInterface(
                f"{delivery_id}.clock2x",
                delivery_id,
                MVAUPhysicalControlKind.CLOCK,
                "ap_clk2x",
            ),
            MVAUPhysicalControlInterface(
                f"{delivery_id}.reset",
                delivery_id,
                MVAUPhysicalControlKind.RESET,
                "ap_rst_n",
            ),
            MVAUPhysicalControlInterface(
                f"{delivery_id}.configuration",
                delivery_id,
                MVAUPhysicalControlKind.CONFIGURATION,
                "s_axilite",
            ),
            MVAUPhysicalControlInterface(
                f"{delivery_id}.set_selector",
                delivery_id,
                MVAUPhysicalControlKind.CONFIGURATION,
                "s_axis_0",
            ),
        )
        components += (delivery_component,)
        interfaces += (delivery_interface,)
        controls += delivery_controls
        connections += (
            MVAUPhysicalConnection(
                "network.delivery_to_compute",
                (delivery_interface.id, f"{wrapper_id}.weight"),
                (DELIVERY_EDGE,),
            ),
        )
    interfaces_by_id = {item.id: item for item in interfaces}
    boundary_interface = {
        (REPLAY_NODE, "activation_in"): f"{wrapper_id}.activation",
        (DOT_PRODUCT_NODE, "weight"): f"{wrapper_id}.weight",
        (DOT_PRODUCT_NODE, "output"): f"{wrapper_id}.output",
    }
    boundaries = tuple(
        MVAUPhysicalBoundary(
            boundary.id,
            boundary_interface[(boundary.endpoint.node_id, boundary.endpoint.port_id)],
            MVAUSemanticPortRef(boundary.endpoint.node_id, boundary.endpoint.port_id),
        )
        for boundary in network.boundaries
    )

    owners = (
        resolved.result.source_association.source_node_id,
        *resolved.result.source_association.fused_source_node_ids,
    )
    # Provenance is per binding, not one payload shared by everything.  A single
    # merged record makes the replay component claim the dot product's Kernel
    # and the dot product claim the replay's, which is worse than saying
    # nothing: it is a specific false statement about what realizes what.
    from finn.dataflow.mvau.designs.inventory import MVAU_DESIGN_INVENTORY  # noqa: PLC0415

    design_path = MVAU_DESIGN_INVENTORY.inventory.design_path
    new_inventory = design_path is not None and design_path in resolved.point.design_space.decisions
    by_component = {
        replay_id: _provenance(
            replay,
            None if new_inventory else ActivationReplayKernel.id,
            None if new_inventory else MVAU_REPLAY_SELECTION.paths.kernel,
            network,
        ),
        dot_id: _provenance(
            compute,
            None if new_inventory else DotProductKernel.id,
            None if new_inventory else MVAU_COMPUTE_SELECTION.paths.kernel,
            network,
        ),
    }
    if delivery is not None:
        by_component[f"{source_id}.delivery.wrapper"] = _provenance(
            delivery,
            None if new_inventory else FINN_RTL_MEMSTREAM_SUPPLY,
            QualifiedPath("mvau.input.weight.supply"),
            network,
        )
    # The wrapper and every connection through it span both, so their record is
    # the union -- which is what a union is for, rather than the default.
    everything_covered = _merge(tuple(by_component.values()))
    by_component[wrapper_id] = everything_covered

    def association(
        physical_id: str,
        provenance: _Provenance,
        ports: tuple[MVAUSemanticPortRef, ...] | None = None,
        edges: tuple[str, ...] = (),
    ) -> MVAUPhysicalAssociation:
        return MVAUPhysicalAssociation(
            physical_id,
            owners,
            provenance.regions,
            provenance.ports if ports is None else ports,
            edges,
            provenance.decisions,
            provenance.kernels,
            (),
        )

    associations = (
        *(association(item.id, by_component[item.id]) for item in components),
        # An interface belongs to exactly one component, and its semantic ports
        # are already declared on it -- so it inherits that component's record
        # and narrows the ports to the ones it actually carries.
        *(
            association(item.id, by_component[item.component_id], item.semantic_ports)
            for item in interfaces
        ),
        # A connection spans the components it joins.
        *(
            association(
                item.id,
                _merge(
                    tuple(
                        by_component[interfaces_by_id[interface].component_id]
                        for interface in item.interface_ids
                    )
                ),
                edges=item.semantic_edge_ids,
            )
            for item in connections
        ),
        # Clocks and reset, which had no record at all until Phase 6g.
        #
        # They carry no semantic *port*, and that is right: no Region port is a
        # clock, and the nets themselves are the enclosing design's -- this unit
        # cannot name them.  But "no semantic referent" is not "no provenance".
        # ``ap_clk2x`` exists because ``compute_pumping`` is a decision this
        # design space carries, so a doubled clock with nothing saying which
        # choice put it there is exactly the gap the association ledger exists
        # to close.  The ports are explicitly empty rather than inherited,
        # because inheriting the component's would claim a clock carries the
        # activation stream.
        *(association(item.id, by_component[item.component_id], ()) for item in controls),
    )
    return MVAUPhysicalElaboration(
        source_id,
        mvau_elaboration_origin(resolved) if origin is None else origin,
        resolved.result,
        cast(str, resolved.point.problem[MVAUProblemPaths.TARGET_FPGA_PART]),
        cast(float, resolved.point.problem[MVAUProblemPaths.TARGET_CLOCK_PERIOD_NS]),
        components,
        interfaces,
        controls,
        connections,
        boundaries,
        associations,
    )


# -- artifact requirements ---------------------------------------------------


@dataclass(frozen=True)
class MVAUDecomposedArtifactRequirements:
    """Everything needed to produce the decomposed RTL, and nothing ambient.

    Deliberately not ``MVAURTLArtifactRequirements``: that value exists to drive
    the legacy ``MVAU_rtl`` custom op, which emits the fused core and cannot emit
    this one.  The decomposed path generates its own top, so it carries the
    generated text rather than the inputs to someone else's generator.
    """

    top_module_name: str
    target_fpga_part: str
    clock_period_ns: float
    parameters: tuple[tuple[str, bool | int | float | str], ...]
    #: ``(id, absolute path)`` in compile order.
    source_dependencies: tuple[tuple[str, str], ...]
    wrapper_file_name: str
    wrapper_source: str
    #: The plain-Verilog top a block design can reference, and its text.  A
    #: ``.sv`` top cannot be a ``create_bd_cell -type module`` reference, so
    #: without this the unit is buildable and not stitchable.
    stitch_file_name: str
    stitch_source: str
    elaboration: MVAUPhysicalElaboration
    #: What this artifact *is*, keyed by its physical inputs alone.  Computed
    #: before any builder runs, which is what makes it usable as a lookup.
    identity: ComposedArtifactIdentity
    #: Non-HDL files consumed by generated RTL, as relative name and text.
    data_files: tuple[tuple[str, str], ...] = ()

    @property
    def stitch_module_name(self) -> str:
        """What a block design references -- the shim, not the generated top."""

        return f"{self.top_module_name}_wrapper"

    @property
    def finnlib_sources(self) -> tuple[str, ...]:
        return tuple(path for name, path in self.source_dependencies if ".finnlib." in name)


def decomposed_top_module_name(kernels: tuple[KernelArtifactIdentity, ...]) -> str:
    """A module name derived from the configuration, and from nothing placed.

    It used to be ``{source_node_id}_decomposed``, which is why two identical
    MVAUs at different graph positions were two builds.  Naming the module from
    the artifact key instead is circular -- the name is inside the wrapper text
    and the wrapper text is inside the key -- so the name is taken over the
    part of the Kernel identities that exists before the wrapper does.

    Sources are deliberately *excluded* even though they are in the key.  A
    name that moved whenever a FinnLib file was edited would churn every
    recorded fixture for a change that does not alter the configuration, and
    the name has only to separate configurations: two builds differing only in
    source content already land under different keys, and are never stitched
    into one design from the same configuration.
    """

    material = _canonical_configuration(kernels)
    return f"mvau_decomposed_{content_hash(material.encode())[:12]}"


def _canonical_configuration(kernels: tuple[KernelArtifactIdentity, ...]) -> str:
    return "\n".join(
        "|".join(
            (
                item.kernel_id,
                item.kernel_version,
                *(f"{name}={_literal(value)}" for name, value in item.parameters),
                *(f"@{name}={_literal(value)}" for name, value in item.assignments),
            )
        )
        for item in kernels
    )


def build_decomposed_artifact_requirements(
    resolved: MVAUResolvedDesign,
    elaboration: MVAUPhysicalElaboration,
    finn_root: str | Path,
    finnlib: str | Path | None = None,
) -> MVAUDecomposedArtifactRequirements:
    """Turn a decomposed elaboration into a self-contained build input.

    The identity is computed here, before anything is written, because a
    lookup that can only be performed after the build has run is not a lookup.

    It takes no builder and no target.  Neither reaches the generated text --
    Vivado is not invoked to produce it, and every way the target reaches the
    RTL is already a declared parameter -- so both belong to the stage that
    consumes them.  The part and clock stay on the requirements because a
    synthesizer needs them; they are simply not part of *this* key.
    """

    if elaboration.origin != mvau_elaboration_origin(resolved):
        raise _fail(
            "mvau-decomposed-origin-mismatch",
            "the elaboration was not produced from this exact selected point",
        )
    if elaboration.semantic_result != resolved.result:
        raise _fail(
            "mvau-decomposed-result-mismatch",
            "the elaboration does not belong to the selected semantic result",
        )
    realization = bind_decomposed(resolved)
    roots = source_roots(finn_root, finnlib)
    kernels = tuple(
        kernel_artifact_identity(realization.kernel(placement), roots)
        for placement in ("replay", "compute")
    )
    top = decomposed_top_module_name(kernels)
    wrapper = elaboration.component(
        f"{resolved.result.source_association.source_node_id}.compute.wrapper"
    )
    replay = realization.kernel("replay")
    compute = realization.kernel("compute")
    replay_region = replay.regions["replay"].region
    compute_region = compute.regions["compute"].region
    text = render_decomposed_wrapper(
        top,
        dict(replay.parameters),
        dict(compute.parameters),
        activation_bits=replay_region.input_interface("activation_in").port.logical_beat_bits,
        weight_bits=compute_region.input_interface("weight").port.logical_beat_bits,
        output_bits=compute_region.output_interface("output").port.logical_beat_bits,
    )
    shim = render_stitch_shim(
        top,
        activation_bits=replay_region.input_interface("activation_in").port.logical_beat_bits,
        weight_bits=compute_region.input_interface("weight").port.logical_beat_bits,
        output_bits=compute_region.output_interface("output").port.logical_beat_bits,
    )
    return MVAUDecomposedArtifactRequirements(
        top,
        elaboration.target_fpga_part,
        elaboration.target_clock_period_ns,
        wrapper.parameters,
        resolved_manifest(realization, roots),
        f"{top}.sv",
        text,
        f"{top}_wrapper.v",
        shim,
        elaboration,
        composed_artifact_identity(kernels, text, shim),
    )


def staged_layout(requirements: MVAUDecomposedArtifactRequirements) -> tuple[str, ...]:
    """The staged file *names*, relative to the unit directory, in compile order.

    Names and not paths.  This is what a packaged identity is taken over, and
    an artifact does not become a different artifact because it was written
    under another root -- so a materialized path can never be an input to it.
    """

    return (
        *(f"{name}_{Path(path).name}" for name, path in requirements.source_dependencies),
        *(name for name, _contents in requirements.data_files),
        requirements.wrapper_file_name,
        requirements.stitch_file_name,
    )


def write_decomposed_artifact(
    requirements: MVAUDecomposedArtifactRequirements, output_directory: str | Path
) -> tuple[str, ...]:
    """Stage the declared sources and the generated top, in compile order.

    Returns the file list a simulator or synthesizer should read, with the
    generated wrapper last because it instantiates everything before it.

    Staging only.  The store is consulted by
    :func:`package_decomposed_artifact`, which is the build path and the thing
    that owns a stage key; asking here as well would consult twice with two
    different keys for one build.
    """

    verify_manifest(requirements.source_dependencies)
    output = Path(output_directory).resolve()
    output.mkdir(parents=True, exist_ok=True)
    staged: list[str] = []
    for name, path in requirements.source_dependencies:
        destination = output / f"{name}_{Path(path).name}"
        destination.write_bytes(Path(path).read_bytes())
        staged.append(str(destination))
    for name, contents in requirements.data_files:
        destination = output / name
        destination.write_text(contents)
        staged.append(str(destination))
    wrapper = output / requirements.wrapper_file_name
    wrapper.write_text(requirements.wrapper_source)
    staged.append(str(wrapper))
    shim = output / requirements.stitch_file_name
    shim.write_text(requirements.stitch_source)
    staged.append(str(shim))
    return tuple(staged)


# -- packaging ---------------------------------------------------------------

#: How this unit is instantiated, as a shape rather than as a command.
#:
#: ``-type module``, which is the documented form for referencing an RTL module
#: added with ``add_files``.  ``matrixvectoractivation_rtl`` uses ``-type hier``
#: for its own generated top and baseline FINN uses ``-type module`` for
#: ``sim_ctrl``; both spellings exist in the tree.  This one is validated --
#: fixture 7 builds a real block design and instantiates the packaged unit, and
#: it is the only reason the choice is stated as fact rather than as preference.
INSTANTIATION_COMMAND_SCHEMA = "create_bd_cell -type module -reference {module} {instance}"


def packaged_artifact_identity(
    requirements: MVAUDecomposedArtifactRequirements,
) -> PackagedArtifactIdentity:
    """Stage two's key, computed before anything is staged.

    Over the generated-source key, the relative layout, and the command shape.
    None of those is a materialized path, so packaging one set of requirements
    under two repository roots is one artifact -- which it is.

    Formed before the build because it has to name the directory and answer a
    lookup.  A key that could only be computed afterwards would be a receipt.
    """

    return PackagedArtifactIdentity(
        requirements.identity.key, staged_layout(requirements), INSTANTIATION_COMMAND_SCHEMA
    )


@dataclass(frozen=True)
class PackagedDecomposedArtifact:
    """The decomposed MVAU as a first-class stitchable unit, materialized.

    Not an ``ipx::`` package.  RTL layers in FINN are not standalone IP:
    ``PrepareIP`` produces filled Verilog to instantiate as a module, and
    ``create_stitched_ip`` adds the codegen directory as an IP repository path
    and emits ``create_bd_cell``.  This is the same shape, which is what makes
    "package the generated wrapper as real IP" mean "make it stitchable" here.

    ``templates.ip_package_tcl`` was the alternative and was rejected on the
    ports: it infers one AXI stream in and one out, where this wrapper has
    ``in0``, ``in1``, ``out0`` and an extra ``ap_clk2x``.  Those are reported
    below rather than inferred, so a consumer that needs a real ``ipx::``
    package later has the interface list to build one from -- an additional
    stage over the same identity, not a redesign.

    The identity is the value; this is one materialization of it.  ``directory``
    and ``files`` are therefore always consistent with each other, including on
    a store hit, where both come from the store.
    """

    identity: PackagedArtifactIdentity
    #: The generated SystemVerilog top: what synthesizes.
    top_module_name: str
    #: The plain-Verilog shim over it: what a block design can reference.
    stitch_module_name: str
    #: The staged directory, usable directly as an ``ip_path``.
    directory: str
    #: Every file to compile, in compile order, generated top last.
    files: tuple[str, ...]
    #: The generated top's own AXI-Stream ports, as elaborated.
    stream_interfaces: tuple[MVAUPhysicalNumericInterface, ...]
    #: Its clocks and reset, likewise -- ``ap_clk2x`` among them.
    control_interfaces: tuple[MVAUPhysicalControlInterface, ...]
    #: True when this unit was returned by a store rather than staged here.
    reused: bool = False

    def __post_init__(self) -> None:
        """The materialization must be the one the identity describes.

        The identity already declares the layout -- which files, named how, in
        what compile order -- so a materialization is checkable against it
        rather than merely plausible.  An earlier version asked only that
        *some* file sit in the reported directory, which a store returning a
        single unrelated file satisfied while the identity declared nine.

        File contents are still the store's word.  Encoded structure is not.
        """

        directory = Path(self.directory)
        outside = tuple(item for item in self.files if Path(item).parent != directory)
        if outside:
            raise ValueError(
                "every file of a packaged unit must live in the directory it "
                f"reports; {directory} does not hold {outside}"
            )
        staged = tuple(Path(item).name for item in self.files)
        if staged != self.identity.layout:
            raise ValueError(
                "a packaged unit's files must be the layout its identity declares, "
                f"in compile order; {self.identity.key} declares "
                f"{self.identity.layout} and this holds {staged}"
            )

    @property
    def key(self) -> str:
        return self.identity.key

    def synthesis_identity(
        self, target: TargetIdentity, builder: BuilderIdentity = DEFAULT_BUILDER
    ) -> SynthesisArtifactIdentity:
        """Stage three's key: this unit, built for a device by a tool.

        The part, the clock, and the builder enter *here* and nowhere lower,
        because this is the stage that consumes them.  One packaged unit
        synthesized for two parts is two results over one source, which is the
        reuse keeping them out of the lower stages buys.

        The constraints and the command shape are inputs too, and they are
        taken from this module rather than supplied: a caller that rendered its
        own constraints and then keyed them would be keying its own text, which
        is not the same claim.
        """

        return SynthesisArtifactIdentity(
            self.identity.key,
            target,
            builder,
            content_hash(render_clock_constraints(target).encode()),
            SYNTHESIS_RECIPE_SCHEMA,
        )

    def ip_package_identity(
        self,
        vlnv: VlnvIdentity = DEFAULT_VLNV,
        fpga_part: str = "",
        builder: BuilderIdentity = DEFAULT_BUILDER,
    ) -> IpPackageArtifactIdentity:
        """The other stage-three key: this unit as an IP-XACT component.

        A sibling of :meth:`synthesis_identity`, not a step after it.  Both take
        the packaged unit as upstream and neither reads the other, so the two
        can be produced in either order or not at all.

        No clock period.  Nothing in packaging reads one, and a key carrying a
        value that cannot change what is produced is a way to *miss* a valid
        reuse -- as wrong as a wrong hit and quieter.
        """

        return IpPackageArtifactIdentity(
            self.identity.key, vlnv, fpga_part, builder, IP_PACKAGE_RECIPE_SCHEMA
        )

    def instantiation_commands(self, instance_name: str) -> tuple[str, ...]:
        """The IPI commands that place this unit, at a caller-chosen instance.

        The instance name is an argument and not a field: it is placement, and
        placement is what the whole phase took out of the artifact.  One
        packaged unit instantiated twice is two cells over one build, which is
        the reuse this was all for.

        Clock and reset nets are the caller's -- they are the enclosing block
        design's, and this unit cannot name them.  ``control_interfaces``
        reports the pins that have to be driven, ``ap_clk2x`` included.
        """

        if not instance_name:
            raise ValueError("an instantiated cell needs a name")
        return (
            *(f"add_files -norecurse {path}" for path in self.files),
            INSTANTIATION_COMMAND_SCHEMA.format(
                module=self.stitch_module_name, instance=instance_name
            ),
        )


def packaged_directory_name(identity: PackagedArtifactIdentity, top_module_name: str) -> str:
    """Where a packaged unit lives: addressed by identity, readable by module.

    The key alone would do and would be unreadable in a build tree; the module
    name alone is a digest over the configuration and says nothing about the
    sources.  Both, so that two artifacts differing only in source content are
    visibly two directories.
    """

    return f"{top_module_name}_{identity.key[:16]}"


def package_decomposed_artifact(
    requirements: MVAUDecomposedArtifactRequirements,
    repository_root: str | Path,
    *,
    store: ArtifactStore = NO_ARTIFACT_STORE,
) -> PackagedDecomposedArtifact:
    """Stage the decomposed artifact under an identity-addressed directory.

    This is the build path, so this is where the store is consulted -- with
    *this* stage's key, and through :func:`checked_lookup`, which refuses an
    answer about some other artifact rather than building with it.

    ``repository_root`` is the IP repository; the unit's own directory beneath
    it is named from the identity rather than chosen by the caller, because a
    caller-chosen path is how two builds of one artifact end up in two places
    with nothing saying they are the same.
    """

    identity = packaged_artifact_identity(requirements)
    wrapper_id = f"{requirements.elaboration.source_scope_id}.compute.wrapper"
    boundary_interfaces = {
        boundary.interface_id for boundary in requirements.elaboration.boundaries
    }
    interfaces = tuple(
        item
        for item in requirements.elaboration.numeric_interfaces
        if item.id in boundary_interfaces
    )
    selected_controls = tuple(
        item
        for item in requirements.elaboration.control_interfaces
        if item.component_id == wrapper_id or item.kind is MVAUPhysicalControlKind.CONFIGURATION
    )
    controls = tuple(
        next(item for item in selected_controls if (item.kind, item.signal) == identity)
        for identity in dict.fromkeys((item.kind, item.signal) for item in selected_controls)
    )
    found = checked_lookup(store, identity)
    if found is not None:
        # The store's directory, not one computed here: a unit that reports a
        # directory its files are not in describes nothing that exists.
        return PackagedDecomposedArtifact(
            identity,
            requirements.top_module_name,
            requirements.stitch_module_name,
            found.directory,
            found.files,
            interfaces,
            controls,
            reused=True,
        )
    directory = Path(repository_root).resolve() / packaged_directory_name(
        identity, requirements.top_module_name
    )
    return PackagedDecomposedArtifact(
        identity,
        requirements.top_module_name,
        requirements.stitch_module_name,
        str(directory),
        write_decomposed_artifact(requirements, directory),
        interfaces,
        controls,
    )


# -- out-of-context synthesis ------------------------------------------------

#: The synthesis command, as a shape rather than as a command.
#:
#: In the key, so that changing an option -- ``-mode out_of_context`` above
#: all -- changes what the stage is keyed on.  A *rendered* command would carry
#: absolute source and report paths, which is the trap the packaged layout
#: already avoids by holding names instead.
SYNTHESIS_RECIPE_SCHEMA = "\n".join(
    (
        "{sources}",
        "read_xdc {constraints}",
        "synth_design -top {top} -part {part} -mode out_of_context",
        "report_utilization -file {report}",
    )
)

#: The two files a synthesis run reads that the packaged unit does not carry.
CONSTRAINTS_FILE_NAME = "clock.xdc"
SYNTHESIS_SCRIPT_FILE_NAME = "synth.tcl"
UTILIZATION_REPORT_FILE_NAME = "utilization.rpt"


def render_clock_constraints(target: TargetIdentity) -> str:
    """The requested clock, as constraints synthesis is actually run against.

    Here rather than in a fixture, because the constraint text is a build input
    and therefore keyed.  A caller that rendered its own and then hashed it
    would be keying its own text, which is a claim about the caller.

    ``ap_clk2x`` is derived and not chosen: the pumped compute path runs at
    twice the rate, and letting a caller pick a separate number for it would be
    inventing a design input.
    """

    period = target.clock_period_ns
    return (
        f"create_clock -period {period} -name {PRIMARY_CLOCK} "
        f"[get_ports {PRIMARY_CLOCK}]\n"
        f"create_clock -period {period / 2} -name {DOUBLED_CLOCK} "
        f"[get_ports {DOUBLED_CLOCK}]\n"
    )


#: What a completed synthesis run holds, in a fixed order.
#:
#: Declared, so that a store's answer can be checked against it rather than
#: taken on trust -- the same reason the packaged unit declares its layout.  A
#: run also leaves tool droppings (``.Xil``, journals, checkpoints); those are
#: the tool's and are not part of what this stage claims to produce.
SYNTHESIS_LAYOUT = (
    CONSTRAINTS_FILE_NAME,
    SYNTHESIS_SCRIPT_FILE_NAME,
    UTILIZATION_REPORT_FILE_NAME,
)


def _in_directory(directory: str, layout: tuple[str, ...]) -> tuple[str, ...]:
    return tuple(str(Path(directory) / name) for name in layout)


@dataclass(frozen=True)
class PreparedDecomposedSynthesis:
    """A synthesis run that has been set up and not yet performed.

    Distinct from :class:`SynthesizedDecomposedArtifact` on purpose.  One value
    with a ``reused`` flag was carrying two different states -- inputs written
    and no report yet, versus a completed result -- and a consumer could not
    tell from the type whether ``report_path`` named a file that exists.  It
    also let the store's answer be discarded, because a "completed" value could
    be fabricated out of a directory alone.
    """

    identity: SynthesisArtifactIdentity
    #: Where this run's inputs and outputs live.  Never the packaged directory.
    directory: str
    top_module_name: str
    #: The packaged unit's files, read from where they already are.
    sources: tuple[str, ...]
    constraints_path: str
    script_path: str
    #: Where the report *will* be written.  It does not exist yet.
    report_path: str

    @property
    def key(self) -> str:
        return self.identity.key


@dataclass(frozen=True)
class SynthesizedDecomposedArtifact:
    """One completed out-of-context synthesis of a packaged unit.

    Its own directory, named from its own key.  The packaged unit is immutable
    and synthesis is a *different* stage over it, so writing a script, a
    constraints file and a report into the package directory would both mutate
    the artifact and make two runs of one package -- another part, another
    clock, another tool -- overwrite each other.

    ``files`` is checked against :data:`SYNTHESIS_LAYOUT`, so a store answering
    with the right key and the wrong contents is refused rather than believed.
    """

    identity: SynthesisArtifactIdentity
    directory: str
    top_module_name: str
    files: tuple[str, ...]
    reused: bool = False

    def __post_init__(self) -> None:
        expected = _in_directory(self.directory, SYNTHESIS_LAYOUT)
        if self.files != expected:
            raise ValueError(
                "a completed synthesis must hold the layout this stage declares; "
                f"{self.identity.key} expects {SYNTHESIS_LAYOUT} under "
                f"{self.directory} and this holds {self.files}"
            )

    @property
    def key(self) -> str:
        return self.identity.key

    def _named(self, name: str) -> str:
        return self.files[SYNTHESIS_LAYOUT.index(name)]

    @property
    def constraints_path(self) -> str:
        return self._named(CONSTRAINTS_FILE_NAME)

    @property
    def script_path(self) -> str:
        return self._named(SYNTHESIS_SCRIPT_FILE_NAME)

    @property
    def report_path(self) -> str:
        return self._named(UTILIZATION_REPORT_FILE_NAME)


def synthesis_directory_name(identity: SynthesisArtifactIdentity, top_module_name: str) -> str:
    return f"{top_module_name}_synth_{identity.key[:16]}"


def find_decomposed_synthesis(
    packaged: PackagedDecomposedArtifact,
    target: TargetIdentity,
    *,
    builder: BuilderIdentity = DEFAULT_BUILDER,
    store: ArtifactStore = NO_ARTIFACT_STORE,
) -> SynthesizedDecomposedArtifact | None:
    """A run already done for this unit, part, clock, constraints and tool.

    The store's manifest is *consumed*, not discarded.  An earlier version read
    only the directory and fabricated three conventional file names beneath it,
    so a store answering with the right key and a single unrelated file was
    accepted and three paths it had never supplied were reported back.  That is
    the wrong-hit this whole design is against, reached by ignoring the part of
    the answer that says what was found.
    """

    identity = packaged.synthesis_identity(target, builder)
    found = checked_lookup(store, identity)
    if found is None:
        return None
    return SynthesizedDecomposedArtifact(
        identity, found.directory, packaged.top_module_name, found.files, reused=True
    )


def prepare_decomposed_synthesis(
    packaged: PackagedDecomposedArtifact,
    target: TargetIdentity,
    output_root: str | Path,
    *,
    builder: BuilderIdentity = DEFAULT_BUILDER,
) -> PreparedDecomposedSynthesis:
    """Everything a synthesis run consumes, written where its key says.

    It does not invoke anything and it does not look anything up.  Producing a
    script is not running a tool -- keeping that line is what stops
    ``BuilderIdentity`` growing into the execution adapter it was deliberately
    not made -- and the lookup is :func:`find_decomposed_synthesis`, which
    returns a *completed* run rather than a prepared one.
    """

    identity = packaged.synthesis_identity(target, builder)
    directory = Path(output_root).resolve() / synthesis_directory_name(
        identity, packaged.top_module_name
    )
    if directory == Path(packaged.directory):
        raise ValueError("a synthesis run must not materialize into its packaged unit")
    directory.mkdir(parents=True, exist_ok=True)
    constraints = directory / CONSTRAINTS_FILE_NAME
    constraints.write_text(render_clock_constraints(target))
    report = directory / UTILIZATION_REPORT_FILE_NAME
    script = directory / SYNTHESIS_SCRIPT_FILE_NAME
    script.write_text(
        SYNTHESIS_RECIPE_SCHEMA.format(
            sources="\n".join(
                f"read_verilog -sv {{{path}}}"
                for path in packaged.files
                if Path(path).suffix in {".v", ".sv"}
            ),
            constraints=f"{{{constraints}}}",
            top=packaged.top_module_name,
            part=target.fpga_part,
            report=f"{{{report}}}",
        )
        + "\n"
    )
    for path in packaged.files:
        if Path(path).suffix not in {".v", ".sv"}:
            shutil.copy2(path, directory / Path(path).name)
    return PreparedDecomposedSynthesis(
        identity,
        str(directory),
        packaged.top_module_name,
        packaged.files,
        str(constraints),
        str(script),
        str(report),
    )


def complete_decomposed_synthesis(
    prepared: PreparedDecomposedSynthesis,
) -> SynthesizedDecomposedArtifact:
    """The run, once the tool has left its outputs behind.

    Whoever invoked the tool says so by calling this, and it refuses unless the
    declared layout is actually on disk.  A prepared run that turned into a
    completed one without producing a report would otherwise be storable, and a
    later hit would hand a consumer a report that was never written.
    """

    missing = tuple(
        name for name in SYNTHESIS_LAYOUT if not (Path(prepared.directory) / name).is_file()
    )
    if missing:
        raise ValueError(
            f"synthesis under {prepared.directory} did not produce {missing}; "
            "a run is not complete until its declared outputs exist"
        )
    return SynthesizedDecomposedArtifact(
        prepared.identity,
        prepared.directory,
        prepared.top_module_name,
        _in_directory(prepared.directory, SYNTHESIS_LAYOUT),
    )


# -- IP-XACT packaging -------------------------------------------------------
#
# What fixture 7 proves is that the unit is stitchable as a *module*:
# ``add_files`` plus ``create_bd_cell -type module``.  That is enough for a
# block design assembled by hand and not enough for FINN's own stitcher, which
# resolves every layer through ``ip_repo_paths`` and ``create_bd_cell -type ip
# -vlnv``.  This stage is the difference: the same sources, filed as an IP-XACT
# component under a repository coordinate.
#
# It is a sibling of synthesis and not a step after it -- see
# ``IpPackageArtifactIdentity``.

#: The packaging command, as a shape rather than as a command.
#:
#: ``set_property top`` is explicit because the shim and the generated top are
#: two candidates and Vivado's inference picks by heuristic; the unit already
#: says which one a consumer references, so saying it here keeps the two
#: answers from diverging.
#:
#: ``{interfaces}`` is where the unit's own reported names go.  Bus interfaces
#: are inferred **from an explicit port list** and not by letting the packager
#: guess: a component that recorded no AXI-Stream would present loose pins to a
#: stitcher that connects interfaces, and it would do so silently.  Fixture 7
#: saw the inference only because ``create_bd_cell -type module`` re-runs it on
#: the source; a repository coordinate has to carry it.
#:
#: Naming the ports also puts the unit's reported signal names on the path a
#: consumer actually uses -- which is exactly where fixture 7 found them wrong
#: (``in0_V_TDATA`` for a pin spelled ``in0_V_tdata``).
IP_PACKAGE_RECIPE_SCHEMA = "\n".join(
    (
        "create_project -in_memory -part {part}",
        "set_property source_mgmt_mode All [current_project]",
        "{sources}",
        "update_compile_order -fileset sources_1",
        "set_property top {top} [current_fileset]",
        # No ``-taxonomy``.  It is a catalog category with no effect on what is
        # produced, and its conventional value ``/UserIP`` reads as an absolute
        # path to the command-shape check -- which is the check doing its job on
        # a string that only looks like one.  Removing the option removes a
        # decision rather than hiding it from the key.
        # No ``-module``.  That flag names a *block design* to package -- it is
        # what FINN's stitcher uses, because a stitched IP is a BD -- and given
        # an RTL module name Vivado answers "[Ipptcl 7-538] The block design
        # ... must be opened to package".  An RTL component is packaged from
        # the project's top, which ``set_property top`` above fixes.
        "ipx::package_project -root_dir {root} -vendor {vendor} -library {library} "
        "-import_files -force",
        "set core [ipx::current_core]",
        "set_property version {version} $core",
        "set_property display_name {top} $core",
        "{interfaces}",
        # Every bus parameter becomes user-resolvable.  Packaging an RTL module
        # records whatever the packager inferred -- ``FREQ_HZ`` defaults to
        # 100 MHz for a clock the component knows nothing about -- and a
        # component that pins a frequency it never knew asserts something
        # false: an enclosing design running at 250 MHz then fails validation
        # over a number this unit had no business declaring.  FINN's own
        # stitcher does exactly this, for exactly this reason.
        "set_property value_resolve_type user "
        "[ipx::get_bus_parameters -of [ipx::get_bus_interfaces -of $core]]",
        "ipx::create_xgui_files $core",
        "ipx::update_checksums $core",
        "ipx::save_core $core",
    )
)

#: The abstraction each reported interface is filed under.
AXIS_ABSTRACTION = "xilinx.com:interface:axis_rtl:1.0"
CONTROL_ABSTRACTION = {
    MVAUPhysicalControlKind.CLOCK: "xilinx.com:signal:clock_rtl:1.0",
    MVAUPhysicalControlKind.RESET: "xilinx.com:signal:reset_rtl:1.0",
}


def ip_interface_commands(packaged: PackagedDecomposedArtifact) -> tuple[str, ...]:
    """One ``infer_bus_interface`` per interface the unit publishes.

    Built from ``stream_interfaces`` and ``control_interfaces`` rather than
    from a list written here.  A packaged unit that reported an interface it
    did not have would previously fail only in a block design; now it fails in
    its own component description, which is the earlier of the two.

    A ``CONFIGURATION`` control has no signal abstraction and is skipped -- it
    is a parameter rather than a pin, and inferring one would name something
    that is not a port.
    """

    commands = [
        f"ipx::infer_bus_interface "
        f"{{{item.data_signal} {item.valid_signal} {item.ready_signal}}} "
        f"{AXIS_ABSTRACTION} $core"
        for item in packaged.stream_interfaces
    ]
    commands.extend(
        f"ipx::infer_bus_interface {item.signal} {CONTROL_ABSTRACTION[item.kind]} $core"
        for item in packaged.control_interfaces
        if item.kind in CONTROL_ABSTRACTION
    )
    # Every stream is synchronous to the primary clock, and the component has
    # to say so.  Without the association the packager records whatever
    # ``FREQ_HZ`` it inferred -- 100 MHz, a number this unit never knew -- and
    # an enclosing design running at anything else fails validation on it.  A
    # component that pins a frequency it was never told is asserting something
    # false; associating the clock is how it says "whatever drives me".
    commands.extend(
        f"ipx::associate_bus_interfaces -busif {_bus_name(item)} -clock {PRIMARY_CLOCK} $core"
        for item in packaged.stream_interfaces
    )
    commands.append(
        f"ipx::associate_bus_interfaces -clock {PRIMARY_CLOCK} -reset {RESET_SIGNAL} $core"
    )
    return tuple(commands)


def _bus_name(interface: MVAUPhysicalNumericInterface) -> str:
    """The interface name inference gives one stream.

    ``<prefix>_tdata``/``_tvalid``/``_tready`` are grouped under ``<prefix>``,
    so the name follows from the signals the unit already publishes rather than
    from a table written here.
    """

    return interface.data_signal.rsplit("_", 1)[0]


#: The IP-XACT description ``ipx::save_core`` leaves behind.  The name is fixed
#: by the standard, which is why one file is a layout: a run that produced a
#: directory without it produced no component.
COMPONENT_FILE_NAME = "component.xml"
IP_PACKAGE_SCRIPT_FILE_NAME = "package_ip.tcl"


def ip_package_directory_name(identity: IpPackageArtifactIdentity, top_module_name: str) -> str:
    return f"{top_module_name}_ip_{identity.key[:16]}"


@dataclass(frozen=True)
class PreparedIpPackage:
    """A packaging run set up and not yet performed.

    The same split as :class:`PreparedDecomposedSynthesis`, for the same
    reason: one type with a flag would let a consumer read ``component_path``
    without being able to tell from the type whether it names a file.
    """

    identity: IpPackageArtifactIdentity
    #: The repository directory this component will occupy.  Never the packaged
    #: unit's -- packaging reads that unit and must not write into it.
    directory: str
    top_module_name: str
    #: What a consumer references once this is packaged.  The shim, because a
    #: ``.sv`` top cannot be a block-design reference; see ``render_stitch_shim``.
    reference_module_name: str
    sources: tuple[str, ...]
    script_path: str
    component_path: str

    @property
    def key(self) -> str:
        return self.identity.key

    @property
    def vlnv(self) -> str:
        """The coordinate a stitcher resolves, in Vivado's own spelling."""

        coordinate = self.identity.vlnv
        return (
            f"{coordinate.vendor}:{coordinate.library}:"
            f"{self.reference_module_name}:{coordinate.version}"
        )


@dataclass(frozen=True)
class PackagedIpComponent:
    """One packaged IP-XACT component, as an IP repository would resolve it.

    ``files`` is checked against the declared layout for the same reason the
    synthesized artifact's is: a store answering with the right key and the
    wrong contents is refused rather than believed.
    """

    identity: IpPackageArtifactIdentity
    directory: str
    top_module_name: str
    reference_module_name: str
    vlnv: str
    files: tuple[str, ...]
    reused: bool = False

    def __post_init__(self) -> None:
        expected = str(Path(self.directory) / COMPONENT_FILE_NAME)
        if expected not in self.files:
            raise ValueError(
                "a packaged IP must hold the component description this stage "
                f"declares; {self.identity.key} expects {expected} and this holds "
                f"{self.files}"
            )

    @property
    def key(self) -> str:
        return self.identity.key

    @property
    def component_path(self) -> str:
        return str(Path(self.directory) / COMPONENT_FILE_NAME)

    def instantiation_commands(self, instance_name: str) -> tuple[str, ...]:
        """How FINN's stitcher places a layer: a repository and a VLNV.

        Deliberately *not* ``add_files`` plus ``-type module``, which is what
        the packaged unit offers.  That form asks the enclosing project to
        compile the sources itself; this one asks it to resolve a component,
        which is the form ``CreateStitchedIP`` emits for every other layer.

        ``set_property ip_repo_paths`` is emitted per call rather than once,
        because a caller placing two cells has to be able to run each cell's
        commands verbatim and get a working design -- exactly as the packaged
        unit's ``add_files`` repeat.  Vivado takes the last value, so the caller
        deduplicates if it wants to; nothing here depends on it.
        """

        if not instance_name:
            raise ValueError("an instantiated cell needs a name")
        return (
            f"set_property ip_repo_paths {self.directory} [current_project]",
            "update_ip_catalog -rebuild",
            f"create_bd_cell -type ip -vlnv {self.vlnv} {instance_name}",
        )


def find_ip_package(
    packaged: PackagedDecomposedArtifact,
    fpga_part: str,
    *,
    vlnv: VlnvIdentity = DEFAULT_VLNV,
    builder: BuilderIdentity = DEFAULT_BUILDER,
    store: ArtifactStore = NO_ARTIFACT_STORE,
) -> PackagedIpComponent | None:
    """A component already packaged for this unit, coordinate, part and tool.

    The store's manifest is consumed rather than reconstructed, for the reason
    the synthesis lookup records: fabricating conventional file names under a
    supplied directory accepts an answer that never contained them.
    """

    identity = packaged.ip_package_identity(vlnv, fpga_part, builder)
    found = checked_lookup(store, identity)
    if found is None:
        return None
    return PackagedIpComponent(
        identity,
        found.directory,
        packaged.top_module_name,
        packaged.stitch_module_name,
        f"{vlnv.vendor}:{vlnv.library}:{packaged.stitch_module_name}:{vlnv.version}",
        found.files,
        reused=True,
    )


def prepare_ip_package(
    packaged: PackagedDecomposedArtifact,
    fpga_part: str,
    output_root: str | Path,
    *,
    vlnv: VlnvIdentity = DEFAULT_VLNV,
    builder: BuilderIdentity = DEFAULT_BUILDER,
) -> PreparedIpPackage:
    """Everything a packaging run consumes, written where its key says.

    It invokes nothing.  Producing a ``.tcl`` is not running Vivado, and the
    lookup is :func:`find_ip_package`, which returns a *packaged* component
    rather than a prepared one.
    """

    identity = packaged.ip_package_identity(vlnv, fpga_part, builder)
    directory = Path(output_root).resolve() / ip_package_directory_name(
        identity, packaged.top_module_name
    )
    if directory == Path(packaged.directory):
        raise ValueError("an IP package must not materialize into its packaged unit")
    directory.mkdir(parents=True, exist_ok=True)
    script = directory / IP_PACKAGE_SCRIPT_FILE_NAME
    script.write_text(
        IP_PACKAGE_RECIPE_SCHEMA.format(
            part=fpga_part,
            sources="\n".join(f"add_files -norecurse {{{path}}}" for path in packaged.files),
            top=packaged.stitch_module_name,
            root=f"{{{directory}}}",
            vendor=vlnv.vendor,
            library=vlnv.library,
            version=vlnv.version,
            interfaces="\n".join(ip_interface_commands(packaged)),
        )
        + "\n"
    )
    return PreparedIpPackage(
        identity,
        str(directory),
        packaged.top_module_name,
        packaged.stitch_module_name,
        packaged.files,
        str(script),
        str(directory / COMPONENT_FILE_NAME),
    )


def complete_ip_package(prepared: PreparedIpPackage) -> PackagedIpComponent:
    """The run, once the tool has written a component description.

    Whoever invoked Vivado says so by calling this, and it refuses unless the
    component exists.  ``ipx::package_project`` also leaves ``xgui/`` and a
    ``src/`` copy behind; those are the tool's and are reported as found rather
    than declared, because their names are Vivado's to choose.
    """

    component = Path(prepared.component_path)
    if not component.is_file():
        raise ValueError(
            f"packaging under {prepared.directory} produced no {COMPONENT_FILE_NAME}; "
            "a run is not complete until its declared output exists"
        )
    return PackagedIpComponent(
        prepared.identity,
        prepared.directory,
        prepared.top_module_name,
        prepared.reference_module_name,
        prepared.vlnv,
        (str(component),),
    )


__all__ = [
    "AXIS_ABSTRACTION",
    "COMPONENT_FILE_NAME",
    "CONTROL_ABSTRACTION",
    "CONSTRAINTS_FILE_NAME",
    "INSTANTIATION_COMMAND_SCHEMA",
    "IP_PACKAGE_RECIPE_SCHEMA",
    "IP_PACKAGE_SCRIPT_FILE_NAME",
    "SYNTHESIS_LAYOUT",
    "SYNTHESIS_RECIPE_SCHEMA",
    "SYNTHESIS_SCRIPT_FILE_NAME",
    "UTILIZATION_REPORT_FILE_NAME",
    "DOUBLED_CLOCK",
    "PRIMARY_CLOCK",
    "RESET_SIGNAL",
    "WRAPPER_MODULE",
    "MVAUDecomposedArtifactRequirements",
    "PackagedDecomposedArtifact",
    "PackagedIpComponent",
    "PreparedDecomposedSynthesis",
    "PreparedIpPackage",
    "SynthesizedDecomposedArtifact",
    "build_decomposed_artifact_requirements",
    "compose",
    "decomposed_top_module_name",
    "elaborate_decomposed",
    "complete_decomposed_synthesis",
    "complete_ip_package",
    "find_decomposed_synthesis",
    "find_ip_package",
    "ip_interface_commands",
    "ip_package_directory_name",
    "prepare_decomposed_synthesis",
    "prepare_ip_package",
    "render_clock_constraints",
    "synthesis_directory_name",
    "package_decomposed_artifact",
    "packaged_artifact_identity",
    "packaged_directory_name",
    "render_decomposed_wrapper",
    "render_stitch_shim",
    "staged_layout",
    "write_decomposed_artifact",
]
