# Copyright (C) 2026, Advanced Micro Devices, Inc.
# SPDX-License-Identifier: BSD-3-Clause

"""Generated artifact inputs for DotProduct with FINN RTL memstream supply."""

from __future__ import annotations

from collections.abc import Mapping
from math import ceil, log2
from pathlib import Path
from typing import cast

import numpy as np  # type: ignore[import-not-found]
from qonnx.core.datatype import DataType  # type: ignore[import-not-found]
from finn.dataflow.authoring.design import DesignRealization
from finn.dataflow.hardware import composed_artifact_identity, kernel_artifact_identity
from finn.dataflow.mvau.elaboration import MVAUPhysicalElaboration
from finn.dataflow.mvau.hardware.binding import source_roots
from finn.dataflow.mvau.hardware.composition import (
    MVAUDecomposedArtifactRequirements,
    decomposed_top_module_name,
    render_decomposed_wrapper,
)
from finn.dataflow.mvau.hardware.memstream import FINN_MEMSTREAM_SOURCES
from finn.dataflow.mvau.source import MVAUResolvedDesign
from finn.dataflow.mvau_problem import MVAUProblemPaths
from finn.dataflow.region import NumericElementType, Port


def _literal(value: object) -> str:
    return str(int(value)) if isinstance(value, bool) else str(value)


def _byte_aligned(bits: int) -> int:
    return ((bits + 7) // 8) * 8


def render_memstream_wrapper(
    template: str,
    module_name: str,
    parameters: Mapping[str, object],
) -> str:
    """Fill FINN's memstream template from one configured Kernel."""

    rendered = template
    replacements = {
        "$MODULE_NAME$": module_name,
        "$SETS$": _literal(parameters["SETS"]),
        "$DEPTH$": _literal(parameters["DEPTH"]),
        "$WIDTH$": _literal(parameters["WIDTH"]),
        "$INIT_FILE$": str(parameters["INIT_FILE"]),
        "$RAM_STYLE$": str(parameters["RAM_STYLE"]),
        "$PUMPED_MEMORY$": _literal(parameters["PUMPED_MEMORY"]),
    }
    for token, value in replacements.items():
        rendered = rendered.replace(token, value)
    return rendered


def _supplied_ports(
    *, activation_bits: int, output_bits: int, address_bits: int
) -> tuple[tuple[str, str, int | None], ...]:
    return (
        ("ap_clk", "input", None),
        ("ap_clk2x", "input", None),
        ("ap_rst_n", "input", None),
        ("s_axilite_AWREADY", "output", None),
        ("s_axilite_AWVALID", "input", None),
        ("s_axilite_AWPROT", "input", 3),
        ("s_axilite_AWADDR", "input", address_bits),
        ("s_axilite_WREADY", "output", None),
        ("s_axilite_WVALID", "input", None),
        ("s_axilite_WDATA", "input", 32),
        ("s_axilite_WSTRB", "input", 4),
        ("s_axilite_BREADY", "input", None),
        ("s_axilite_BVALID", "output", None),
        ("s_axilite_BRESP", "output", 2),
        ("s_axilite_ARREADY", "output", None),
        ("s_axilite_ARVALID", "input", None),
        ("s_axilite_ARPROT", "input", 3),
        ("s_axilite_ARADDR", "input", address_bits),
        ("s_axilite_RREADY", "input", None),
        ("s_axilite_RVALID", "output", None),
        ("s_axilite_RRESP", "output", 2),
        ("s_axilite_RDATA", "output", 32),
        ("s_axis_0_tready", "output", None),
        ("s_axis_0_tvalid", "input", None),
        ("s_axis_0_tdata", "input", 1),
        ("in0_V_tdata", "input", activation_bits),
        ("in0_V_tvalid", "input", None),
        ("in0_V_tready", "output", None),
        ("out0_V_tdata", "output", output_bits),
        ("out0_V_tvalid", "output", None),
        ("out0_V_tready", "input", None),
    )


def _port_declarations(ports: tuple[tuple[str, str, int | None], ...]) -> str:
    return ",\n    ".join(
        f"{direction} wire {f'[{width - 1}:0] ' if width is not None else ''}{name}"
        for name, direction, width in ports
    )


def _connections(names: tuple[str, ...]) -> str:
    return ",\n        ".join(f".{name}({name})" for name in names)


def render_supplied_top(
    module_name: str,
    compute_module: str,
    delivery_module: str,
    *,
    activation_bits: int,
    weight_bits: int,
    output_bits: int,
    address_bits: int,
) -> str:
    """Wire the generated memstream into the generated DotProduct wrapper."""

    ports = _supplied_ports(
        activation_bits=activation_bits,
        output_bits=output_bits,
        address_bits=address_bits,
    )
    delivery_names = tuple(
        name for name, _direction, _width in ports if not name.startswith(("in0_V_", "out0_V_"))
    )
    delivery_connections = _connections(
        (*delivery_names, "weight_tready", "weight_tvalid", "weight_tdata")
    ).replace(".weight_", ".m_axis_0_")
    return f"""// Generated by finn.dataflow.mvau.hardware.supplied_artifacts -- do not edit.
module {module_name}(
    {_port_declarations(ports)}
);
    wire [{weight_bits - 1}:0] weight_tdata;
    wire weight_tvalid;
    wire weight_tready;

    {delivery_module}_memstream_wrapper delivery (
        {delivery_connections}
    );

    {compute_module} compute (
        .ap_clk(ap_clk), .ap_clk2x(ap_clk2x), .ap_rst_n(ap_rst_n),
        .in1_V_tdata(weight_tdata), .in1_V_tvalid(weight_tvalid), .in1_V_tready(weight_tready),
        .in0_V_tdata(in0_V_tdata), .in0_V_tvalid(in0_V_tvalid), .in0_V_tready(in0_V_tready),
        .out0_V_tdata(out0_V_tdata), .out0_V_tvalid(out0_V_tvalid),
        .out0_V_tready(out0_V_tready)
    );
endmodule
"""


def render_supplied_stitch_shim(
    module_name: str,
    *,
    activation_bits: int,
    output_bits: int,
    address_bits: int,
) -> str:
    """Plain-Verilog wrapper accepted by ``create_bd_cell -type module``."""

    ports = _supplied_ports(
        activation_bits=activation_bits,
        output_bits=output_bits,
        address_bits=address_bits,
    )
    names = tuple(name for name, _direction, _width in ports)
    return f"""// Generated stitching wrapper -- do not edit.
module {module_name}_wrapper(
    {_port_declarations(ports)}
);
    {module_name} core (
        {_connections(names)}
    );
endmodule
"""


def _memstream_initializer(
    weights: np.ndarray,
    weight_type: NumericElementType,
    *,
    output_port: Port,
    depth: int,
    pumped_memory: bool,
) -> str:
    """Pack weights exactly as the Provider-era FINN RTL memstream path does."""

    matrix = np.asarray(weights, dtype=np.float32)
    export_type = weight_type
    if weight_type == DataType["BIPOLAR"]:
        matrix = (matrix + 1) / 2
        export_type = DataType["BINARY"]
    width = _byte_aligned(output_port.logical_beat_bits)
    digits = width // 4
    packed: list[str] = []
    for beat in output_port.beat_sequence.beats[:depth]:
        word = 0
        for lane, (neuron, column) in enumerate(beat):
            value = matrix[column, neuron]
            encoded = int(value) & ((1 << export_type.bitwidth()) - 1)
            word |= encoded << (lane * export_type.bitwidth())
        packed.append(f"{word:0{digits}x}")
    stream = np.asarray(packed, dtype=object)
    if pumped_memory:
        split = np.zeros([stream.shape[0] * 2], dtype=object)
        for index, word in enumerate(stream):
            split[2 * index] = word[len(word) // 2 :]
            split[2 * index + 1] = word[: len(word) // 2]
        stream = split
    return "".join(f"{word}\n" for word in stream)


def build_supplied_artifact_requirements(
    resolved: MVAUResolvedDesign,
    realization: DesignRealization,
    elaboration: MVAUPhysicalElaboration,
    weights: np.ndarray,
    finn_root: str | Path,
    finnlib: str | Path | None = None,
) -> MVAUDecomposedArtifactRequirements:
    """Build generated, packaged, synthesis, and IP-XACT inputs for D6a."""

    replay = realization.kernel("replay")
    compute = realization.kernel("compute")
    delivery = realization.kernel("delivery")
    roots = source_roots(finn_root, finnlib)
    kernels = tuple(
        kernel_artifact_identity(realization.kernel(placement), roots)
        for placement in ("replay", "compute", "delivery")
    )
    top = decomposed_top_module_name(kernels)
    compute_module = f"{top}_compute"
    delivery_module = f"{top}_delivery"
    replay_region = replay.regions["replay"].region
    compute_region = compute.regions["compute"].region
    activation_bits = _byte_aligned(
        replay_region.input_interface("activation_in").port.logical_beat_bits
    )
    weight_bits = _byte_aligned(compute_region.input_interface("weight").port.logical_beat_bits)
    output_bits = _byte_aligned(compute_region.output_interface("output").port.logical_beat_bits)
    compute_source = render_decomposed_wrapper(
        compute_module,
        dict(replay.parameters),
        dict(compute.parameters),
        activation_bits=activation_bits,
        weight_bits=weight_bits,
        output_bits=output_bits,
    )
    delivery_parameters = dict(delivery.parameters)
    template_path = roots["finn"] / FINN_MEMSTREAM_SOURCES[0]
    delivery_source = render_memstream_wrapper(
        template_path.read_text(), delivery_module, delivery_parameters
    )
    depth = cast(int, delivery_parameters["DEPTH"])
    width = cast(int, delivery_parameters["WIDTH"])
    words_per_beat = (width + 31) // 32
    address_bits = ceil(log2(max(1, depth * (2 ** ceil(log2(words_per_beat)))))) + 2
    top_source = render_supplied_top(
        top,
        compute_module,
        delivery_module,
        activation_bits=activation_bits,
        weight_bits=weight_bits,
        output_bits=output_bits,
        address_bits=address_bits,
    )
    shim = render_supplied_stitch_shim(
        top,
        activation_bits=activation_bits,
        output_bits=output_bits,
        address_bits=address_bits,
    )
    source_dependencies: list[tuple[str, str]] = []
    counts: dict[str, int] = {}
    for placement in ("replay", "compute", "delivery"):
        kernel = realization.kernel(placement)
        for source in kernel.sources:
            if source.path.endswith("memstream_wrapper_template.v"):
                continue
            index = counts.get(source.root, 0)
            counts[source.root] = index + 1
            source_dependencies.append(
                (f"{placement}.{source.root}.{index}", str(roots[source.root] / source.path))
            )
    weight_type = cast(
        NumericElementType, resolved.point.problem[MVAUProblemPaths.WEIGHT_ELEMENT_TYPE]
    )
    delivery_port = realization.network.node("delivery").region.output_interface("weight").port
    initializer = _memstream_initializer(
        weights,
        weight_type,
        output_port=delivery_port,
        depth=depth,
        pumped_memory=cast(bool, delivery_parameters["PUMPED_MEMORY"]),
    )
    wrapper = elaboration.component(
        f"{resolved.result.source_association.source_node_id}.compute.wrapper"
    )
    return MVAUDecomposedArtifactRequirements(
        top,
        cast(str, resolved.point.problem[MVAUProblemPaths.TARGET_FPGA_PART]),
        cast(float, resolved.point.problem[MVAUProblemPaths.TARGET_CLOCK_PERIOD_NS]),
        wrapper.parameters,
        tuple(source_dependencies),
        f"{top}.sv",
        "\n".join((delivery_source, compute_source, top_source)),
        f"{top}_wrapper.v",
        shim,
        elaboration,
        composed_artifact_identity(
            kernels, delivery_source, compute_source, top_source, shim, initializer
        ),
        (("memblock.dat", initializer),),
    )


__all__ = [
    "build_supplied_artifact_requirements",
    "render_memstream_wrapper",
    "render_supplied_stitch_shim",
    "render_supplied_top",
]
